### ISSUE TITLE
Distinguishing questions from logos/OCR technics

### ISSUE THREAD

**Issue by alexfauquette** [openfoodfacts/robotoff#1012]
### Problem

I want to train annotates products with PGI (blue) or PDO (blue) logos

To do so, I can use the following logo annotation

https://hunger.openfoodfacts.org/logos/deep-search?type=label&value=en:pdo
https://hunger.openfoodfacts.org/logos/deep-search?type=label&value=en:pgi

Seems that when a logo is annotated and the product does not already have the label, it generates an insight

Then I can mass answer those questions as I did for nutriscore logo detection in
https://hunger.openfoodfacts.org/inao?valueTag=en:pdo
https://hunger.openfoodfacts.org/inao?valueTag=en:pgi

The problem is that questions are also generated from OCR. So not logo is to display.

For now, I'm simplify fetching the insight details, and if there is no associated crop, display "no logo". 
Technically font-end could filter questions by fetching insights instead of displaying "no logo". But with more than 12k questions and a large proportion of them not having a logo, I'm not sure the server will appreciate this approach.

Would it be possible to either have:
- a flag to know if the question comes from a logo insight (would avoid the useless insight requests)
- a way to only get questions generated from logo detector

**Comment by raphael0202** [comment]
> Seems that when a logo is annotated and the product does not already have the label, it generates an insight

It indeed generates an insight, and this insight is automatically applied (if other conditions for automatic processing hold true, see https://openfoodfacts.github.io/robotoff/explanations/predictions/ for more info about automatic processing).

So it's not useful to try to automatically apply them through Hunger Games, as this mechanism is already supported in Robotoff.
We can of course discuss the automatic processing logic, which is really strict currently.

To answer your question, you can filter insights that were generated from manual annotation with:
- `predictor=universal-logo-detector`
- `data.is_annotation=true`
