### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/robotoff#1019]
### What

- https://github.com/openfoodfacts/robotoff/pull/1017
- Probably fixed by https://github.com/openfoodfacts/robotoff/pull/1016 

Creating robotoff_worker_high_run ... done
msgfmt: error while opening "aa/LC_MESSAGES/robotoff.mo" for writing: Permission denied
msgfmt: error while opening "ach/LC_MESSAGES/robotoff.mo" for writing: Permission denied
msgfmt: error while opening "af/LC_MESSAGES/robotoff.mo" for writing: Permission denied
msgfmt: error while opening "ak/LC_MESSAGES/robotoff.mo" for writing: Permission denied
msgfmt: error while opening "am/LC_MESSAGES/

**Comment by raphael0202** [comment]
This build issue is solved.
