### ISSUE TITLE
Brand detection does not work for M&S

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/robotoff#109]
Brand detection does not work for M&S: ```\nM&S\nEST. 1884```
https://world.openfoodfacts.org/images/products/00156554/1.jpg

**Comment by raphael0202** [comment]
Can you provide more information ? Why is it expected to work?

**Comment by teolemon** [comment]
I thought it might be related to the fact that it's 2 to 3 letters ?

**Comment by raphael0202** [comment]
Yes indeed, the length limit is currently set to 6.
