### ISSUE TITLE
Prioritize insights when there are multiple insights for a product

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/robotoff#1138]
When using Open Food Facts website or Open Food Facts mobile app, several questions can be asked per product.

Sometimes the first question is related to the product quantity, which is less important than category. Sometimes the first question is hard to answer, leading to user's abandon. And sometimes the user doesn't want to answer many questions -- but would be ok for one (feedback from one of our partners).

When a product has several insights, it would be interesting to prioritize them. I would say:
* category at first: it is crucial for the "road to score"; this should be easy to confirm for the user
* then labels?
* then the rest?

**Comment by raphael0202** [comment]
@CharlesNepote now deployed in prod!
