### ISSUE TITLE
Allow to filter insights by `insight_type`

### ISSUE THREAD

**Issue by g123k** [openfoodfacts/robotoff#1139]
Hi everyone,

For the mobile application, we would like to list all questions for labels and categories, for example.
However, your entry point `questions/$barcode` doesn't seem to implement it, as [I can only see in the doc](https://openfoodfacts.github.io/robotoff/references/api/#tag/Questions/paths/~1questions~1%7Bbarcode%7D/get):
- `count`
- `server_type`
- `lang`

Would it be possible to add this filter and reduce the amount of data sent to the app?

Thanks :)

**Comment by g123k** [comment]
Awesome @ReedAndreas, thanks 🤩

**Comment by g123k** [comment]
Is-it deployed @raphael0202? Because with this request, it doesn't filter anything:
https://robotoff.openfoodfacts.org/api/v1/questions/3270160471966?lang=fr&insight_types=brand

**Comment by raphael0202** [comment]
@g123k It's now in prod :)
