### ISSUE TITLE
API to get questions is slow

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/robotoff#1147]
Reported by VaiTon: https://robotoff.openfoodfacts.org/api/v1/questions?count=10 is far too slow.

**Comment by alexgarel** [comment]
We might simply need an index on popularity (didn't check).

**Comment by raphael0202** [comment]
Here is the latency of Robotoff healthcheck ping for the last 7 days: 
![Capture d’écran du 2023-08-07 10-25-49](https://github.com/openfoodfacts/robotoff/assets/9609923/0150f193-f807-4d63-99a7-b34967133018)

With this information in mind, I think we simply run out of gunicorn workers, hence the slowness. I'm considering switching the API framework to FastAPI, to have async support (and be able to serve more requests concurrently).

**Comment by raphael0202** [comment]
I analyzed a standard request (https://robotoff.openfoodfacts.org/api/v1/questions/popular?insight_types=label&value_tag=en:no-gluten&lang=fr&count=1&page=1) with PostgreSQL ANALYZE command and here are the results:

```sql
EXPLAIN ANALYZE SELECT
  "t1"."id",
  "t1"."barcode",
  "t1"."type",
  "t1"."data",
  "t1"."timestamp",
  "t1"."completed_at",
  "t1"."annotation",
  "t1"."annotated_result",
  "t1"."n_votes",
  "t1"."username",
  "t1"."countries",
  "t1"."brands",
  "t1"."process_after",
  "t1"."value_tag",
  "t1"."value",
  "t1"."source_image",
  "t1"."automatic_processing",
  "t1"."server_type",
  "t1"."unique_scans_n",
  "t1"."reserved_barcode",
  "t1"."predictor",
  "t1"."predictor_version",
  "t1"."campaign",
  "t1"."confidence"
FROM
  "product_insight" AS "t1"
  LEFT OUTER JOIN "annotation_vote" AS "t2" ON (
    ("t2"."insight_id" = "t1"."id")
    AND (
      "t2"."device_id" = '6caaaa6f11b19d762d234b4bae481e753f41fd41'
    )
  )
WHERE
  (
    (
      (
        (
          (
            (
              ("t2"."id" IS NULL)
              AND ("t1"."server_type" = 'off')
            )
            AND ("t1"."annotation" IS NULL)
          )
          AND ("t1"."automatic_processing" IS FALSE)
        )
        AND ("t1"."value_tag" = 'en:no-gluten')
      )
      AND ("t1"."type" IN ('label'))
    )
    AND ("t1"."reserved_barcode" IS FALSE)
  )
ORDER BY
  "t1"."unique_scans_n" DESC
LIMIT
  25
OFFSET
  0;
```

| QUERY PLAN                                                                                                                                                                    |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| Limit  (cost=95403.85..95403.85 rows=1 width=394) (actual time=3067.370..3067.377 rows=25 loops=1)                                                                            |
|   ->  Sort  (cost=95403.85..95403.85 rows=1 width=394) (actual time=3067.368..3067.370 rows=25 loops=1)                                                                       |
|         Sort Key: t1.unique_scans_n DESC                                                                                                                                      |
|         Sort Method: top-N heapsort  Memory: 39kB                                                                                                                             |
|         ->  Nested Loop Left Join  (cost=51123.47..95403.84 rows=1 width=394) (actual time=2726.551..3038.507 rows=51291 loops=1)                                             |
|               Join Filter: (t2.insight_id = t1.id)                                                                                                                            |
|               Filter: (t2.id IS NULL)                                                                                                                                         |
|               ->  Bitmap Heap Scan on product_insight t1  (cost=51123.05..95212.24 rows=2854 width=394) (actual time=2726.396..3014.386 rows=51291 loops=1)                   |
|                     Recheck Cond: ((value_tag = 'en:no-gluten'::text) AND (annotation IS NULL))                                                                               |
|                     Filter: ((automatic_processing IS FALSE) AND (reserved_barcode IS FALSE) AND ((server_type)::text = 'off'::text) AND ((type)::text = 'label'::text))      |
|                     Rows Removed by Filter: 4273                                                                                                                              |
|                     Heap Blocks: exact=23054                                                                                                                                  |
|                     ->  BitmapAnd  (cost=51123.05..51123.05 rows=14161 width=0) (actual time=2723.128..2723.128 rows=0 loops=1)                                               |
|                           ->  Bitmap Index Scan on product_insight_value_tag  (cost=0.00..4675.83 rows=58037 width=0) (actual time=55.968..55.968 rows=60184 loops=1)         |
|                                 Index Cond: (value_tag = 'en:no-gluten'::text)                                                                                                |
|                           ->  Bitmap Index Scan on product_insight_annotation  (cost=0.00..46445.54 rows=798548 width=0) (actual time=2663.511..2663.511 rows=791064 loops=1) |
|                                 Index Cond: (annotation IS NULL)                                                                                                              |
|               ->  Materialize  (cost=0.42..20.37 rows=4 width=32) (actual time=0.000..0.000 rows=0 loops=51291)                                                               |
|                     ->  Index Scan using annotation_vote_device_id on annotation_vote t2  (cost=0.42..20.35 rows=4 width=32) (actual time=0.142..0.142 rows=0 loops=1)        |
|                           Index Cond: (device_id = '6caaaa6f11b19d762d234b4bae481e753f41fd41'::text)                                                                          |
| Planning Time: 2.427 ms                                                                                                                                                       |
| Execution Time: 3067.649 ms                                                                                                                                                   |


If we remove the left outer join:

| QUERY PLAN                                                                                                                                                                                                                   |
| ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| Limit  (cost=0.43..6891.66 rows=25 width=394) (actual time=67.088..101.473 rows=25 loops=1)                                                                                                                                  |
|   ->  Index Scan Backward using product_insight_unique_scans_n on product_insight t1  (cost=0.43..786703.36 rows=2854 width=394) (actual time=67.086..101.458 rows=25 loops=1)                                               |
|         Filter: ((annotation IS NULL) AND (automatic_processing IS FALSE) AND (reserved_barcode IS FALSE) AND ((server_type)::text = 'off'::text) AND (value_tag = 'en:no-gluten'::text) AND ((type)::text = 'label'::text)) |
|         Rows Removed by Filter: 10266                                                                                                                                                                                        |
| Planning Time: 2.113 ms                                                                                                                                                                                                      |
| Execution Time: 101.553 ms                                                                                                                                                                                                   |

**Comment by raphael0202** [comment]
Results when using the subquery:

```
| QUERY PLAN                                                                                                                                                                                                                                                |
| --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| Limit  (cost=16.75..21998.07 rows=25 width=403) (actual time=1271.230..5983.870 rows=22 loops=1)                                                                                                                                                          |
|   ->  Index Scan Backward using product_insight_unique_scans_n on product_insight t1  (cost=16.75..790464.88 rows=899 width=403) (actual time=1271.228..5983.848 rows=22 loops=1)                                                                         |
|         Filter: ((annotation IS NULL) AND (automatic_processing IS FALSE) AND (reserved_barcode IS FALSE) AND (NOT (hashed SubPlan 1)) AND ((server_type)::text = 'off'::text) AND (value_tag = 'en:no-gluten'::text) AND ((type)::text = 'label'::text)) |
|         Rows Removed by Filter: 3084544                                                                                                                                                                                                                   |
|         SubPlan 1                                                                                                                                                                                                                                         |
|           ->  Index Scan using annotation_vote_device_id on annotation_vote t2  (cost=0.42..16.31 rows=3 width=16) (actual time=0.024..0.024 rows=0 loops=1)                                                                                              |
|                 Index Cond: (device_id = '6caaaa6f11b19d762d234b4bae481e753f41fd41'::text)                                                                                                                                                                |
| Planning Time: 0.325 ms                                                                                                                                                                                                                                   |
| Execution Time: 5983.932 ms                                                                                                                                                                                                                               |
```

**Comment by raphael0202** [comment]
I tested again using a subquery on PostgreSQL 16:

```sql
EXPLAIN ANALYZE SELECT
  "t1"."id",
  "t1"."barcode",
  "t1"."type",
  "t1"."data",
  "t1"."timestamp",
  "t1"."completed_at",
  "t1"."annotation",
  "t1"."annotated_result",
  "t1"."n_votes",
  "t1"."username",
  "t1"."countries",
  "t1"."brands",
  "t1"."process_after",
  "t1"."value_tag",
  "t1"."value",
  "t1"."source_image",
  "t1"."automatic_processing",
  "t1"."server_type",
  "t1"."unique_scans_n",
  "t1"."reserved_barcode",
  "t1"."predictor",
  "t1"."predictor_version",
  "t1"."campaign",
  "t1"."confidence"
FROM
  "product_insight" AS "t1"
WHERE
  (
    t1.id not in (
      SELECT
        t2.insight_id
      from
        "annotation_vote" AS "t2"
      where
        "t2"."device_id" = 'f6a797dde3d864110a2df031b2228ebc07696c5b'
    )
  )
  AND "t1"."server_type" = 'off'
  AND "t1"."annotation" IS NULL
  AND "t1"."automatic_processing" IS FALSE
  AND "t1"."type" = 'category'
  AND "t1"."reserved_barcode" IS FALSE
ORDER BY
  "t1"."unique_scans_n" DESC
LIMIT
  25
OFFSET
  0;
```

Output:

```sql
                                                                                                      QUERY PLAN                                                                                                       
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=28.93..149.31 rows=25 width=648) (actual time=12.696..62.087 rows=25 loops=1)
   ->  Index Scan Backward using product_insight_unique_scans_n on product_insight t1  (cost=28.93..1222209.82 rows=253821 width=648) (actual time=12.694..62.071 rows=25 loops=1)
         Filter: ((annotation IS NULL) AND (automatic_processing IS FALSE) AND (reserved_barcode IS FALSE) AND (NOT (hashed SubPlan 1)) AND ((server_type)::text = 'off'::text) AND ((type)::text = 'category'::text))
         Rows Removed by Filter: 20000
         SubPlan 1
           ->  Index Scan using annotation_vote_device_id on annotation_vote t2  (cost=0.42..28.48 rows=6 width=16) (actual time=0.106..0.142 rows=7 loops=1)
                 Index Cond: (device_id = 'f6a797dde3d864110a2df031b2228ebc07696c5b'::text)
 Planning Time: 0.663 ms
 Execution Time: 62.457 ms
(9 rows)
```

In by testing it with several parameters, the query takes 80ms-600ms depending on the query, which is much better than the current outer join used.
