### ISSUE TITLE
Create a campaign for the user editor/org-auchan-apaw

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/robotoff#1160]
### Problem

- Create a campaign for the user editor/org-auchan-apaw
- The idea is to focus edits on Auchan, and possibly to give Hunger Games to members of the Auchan organization to see if there's any interest in data augmentation.

**Comment by raphael0202** [comment]
As discussed last week, we can filter on Hunger Games by brand, so this use case is already possible.

**Comment by teolemon** [comment]
https://hunger.openfoodfacts.org/questions?brand=Auchan&sorted=false&type=category
