### ISSUE TITLE
We should tweak the Crowdin config file so that ambiguous lang have their own files

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/robotoff#1164]
Nope, it's just crowdin looping on ambiguous languages like pt_BR and pt_PT, nl_BE and nl_NL, zh_CN and zh_TW, en_AU, en_UK… plus breton (because)
We should tweak the Crowdin config file so that it does not happen (eg each language is mapped to a proper file)

_Originally posted by @teolemon in https://github.com/openfoodfacts/robotoff/issues/1158#issuecomment-1669663618_

**Comment by raphael0202** [comment]
Did it work with your last PR?

**Comment by raphael0202** [comment]
I think this issue is solved, closing.
