### ISSUE TITLE
Whitelisting of brands

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/robotoff#12]
https://world.openfoodfacts.org/store/lidl/brands
https://world.openfoodfacts.org/store/aldi/brands
---
`Hacendado, Eroski, Lidl, Milbona, Sondey, Italiamo, Freshona, Favorina, Alesto, Solevita, Mcennedy, Bellarom, Eridanous, Aldi, Gutbio, Milsani, Trader's Joe, Knorr, Nestle, Ferrero, Milka, Dr. Oetker, Haribo, Royco, Ethiquable, De Cecco, Chabrior, Maggi, Sainsbury's, Tesco, Lutti, Tropicana, Nutella, Panzani, Waitrose, Asda, Morrison's, By Sainsbury's, The co-operative, Heinz, Tesco Finest, Marks & Spencer, Duchy organic, Twinings, Leader Price`

**Comment by teolemon** [comment]
`REWE, Edeka, Gut & Gunstig, Ja!, Alnatura, Kaufland, REWE Beste Wahl, Ehrmann, K-Classic, Dennree, REWE Bio, Edeka Bio, Hipp, Alpenmark, Barilla`

**Comment by teolemon** [comment]
`Conad, Mulino Bianco, Esselunga, San Benedetto, MyProtein`

**Comment by teolemon** [comment]
`Netto, Thiriet, La Vie Claire, Fleury Michon, Grand Jury, Labeyrie, Léa Nature, U Saveurs, Rochambeau, Ducros, Bjorg, Maître Coq, Delpeyrat, Gerblé, Tipiak, La Belle-Îloise, Delpierre, Saupiquet, Teisseire`

**Comment by raphael0202** [comment]
Fixed (commit #50872c656d27717c26e3448bfaf4cfd62428c62a)

**Comment by teolemon** [comment]
De-whitelist Netto (creating false positives). Also I think we can keep the bug open, and add brands on a rolling basis ?

**Comment by teolemon** [comment]
New list (please wait before adding)
```Pepperidge Farm ```

**Comment by teolemon** [comment]
closing, since I found the file, and moving to a broader approch with a blacklist might be the way forward.
