### ISSUE TITLE
Allow to have comments in the brand blacklist

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/robotoff#123]
It's important to understand why we added a term in the brand blacklist, so it should be possible to comment each line.

For example, I added the term "fini" because it has many false positive in french (with "produit fini" and so on). But in the other hand, the brand(s?) "fini" exists: https://world.openfoodfacts.org/brand/fini
It has more than 300 products, it's a big brand. So we should keep memory of that in comments. I would like to add:

```fini # too many false positive in french; beware: Fini brand exists and has more than 300 products```

**Comment by raphael0202** [comment]
it's currently possible to add comment above the brand using `//`. Could it be used here?

**Comment by teolemon** [comment]
@CharlesNepote comments are possible, see above

**Comment by raphael0202** [comment]
Closing this issue, as it's possible to add comments.
