### ISSUE TITLE
Robotoff has automatically applied false quantity on dozens of products

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/robotoff#1288]
We discovered this by searching products higher than 30 Kg (which should be very very rare, if not impossible). A Mirabelle query has found more than [250 products where quantity is greater than 30 Kg and robotoff is the last editor of the product](https://mirabelle.openfoodfacts.org/products?sql=select+code%0D%0A%2C+url+--%2C+creator%2C+created_datetime%0D%0A%2C+last_modified_datetime%0D%0A%2C+last_modified_by+--%2C+product_name%2C+abbreviated_product_name%2C+generic_name%0D%0A%2C+quantity%0D%0A%2C+CAST%28product_quantity+AS+INTEGER%29+as+quant_in_g%0D%0Afrom+%5Ball%5D%0D%0Awhere+quant_in_g+%3E+30000%0D%0Aand+last_modified_by+%3D%3D+%22roboto-app%22%0D%0Aorder+by+quant_in_g%0D%0Alimit+10000) -- this does mean that all the issues come from robotoff but several of them do.

Examples:
* https://world.openfoodfacts.org/product/5904569550615/hummus-kremowy-z-ciecierzycy-klasyczny-zdrowid%C5%82o?rev=7
* https://world.openfoodfacts.org/product/2207885003395?rev=11

Is it possible to have a list of products where Robotoff have applied quantity, with the distinction between automatic and supervised?

## Solution
Either:
* a) stop automatic application of quantity, and let user manually validate this
* b) at least only automatically apply quantity when it is less than 5 kg: heavy products are quite rare and should be validated by humans; do the same for products with more than 10 pieces (eg. 10x33cl)

**Comment by raphael0202** [comment]
This should be solved, please reopen if it happens again.
