### ISSUE TITLE
Compute category predictions for all products without a category prediction

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/robotoff#1307]
### Problem
- Many products still don't have a category prediction, especially not a category prediction with the new system.
- Can the fact that we haven't done the recomputation be related to the fact that it would trigger massive image recomputation ?
- Or to #1251 

### Proposed solution
- Compute category predictions for all products without a category prediction

**Comment by raphael0202** [comment]
Basically we need Triton (the inference server) on GPU to allow easy computation of a category predictions without overloading the server.

**Comment by raphael0202** [comment]
This was launched 2 weeks ago, it's still in progress!

**Comment by raphael0202** [comment]
Done!
