### ISSUE TITLE
Robotoff suggest things that are already entered

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/robotoff#1313]
It's very frequent that Robotoff suggests things that have just been entered. Eg. here it is suggesting me the category "Drinkable yogurts", but as you can see, this category is already entered.
![image](https://github.com/openfoodfacts/openfoodfacts-server/assets/562352/0f55b64d-30d8-4db1-a3be-14271eed015a)

**Comment by alexgarel** [comment]
I also see it while playing hunger-games.

**Comment by teolemon** [comment]
Could it just be a JavaScript issue client side ? The question does not get refreshed in the UI once you answer it ?

**Comment by raphael0202** [comment]
Insights are deleted once Robotoff is noticed about the change, but in case there is a lot of tasks to be performed, it may take a while (especially after bulk updates).
I'm closing this issue, but if you see this again, please provide the barcode so that I can check.
