### ISSUE TITLE
Extract FSC codes using Regex

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/robotoff#135]
```FSC-C135435```
FSC codes are of the form ```FSC-Cxxxxxx```. Extract them from images and store them in packager codes

**Comment by segysego** [comment]
`import re

regex = re.compile('(^FSC-C\d{6})')
matches = []
with open('file.txt', 'r') as file:
    for line in file:
        line = line.strip()
        if regex.match(line):
            matches.append(line)`

**Comment by segysego** [comment]
I think that the following regex is ok, where should it be?

regex = re.compile('FSC-C\d{6}')

**Comment by raphael0202** [comment]
Indeed!
You can add it here: https://github.com/openfoodfacts/robotoff/blob/abc4e695d69fea27b019a517b8ccb634ce35b2b8/robotoff/insights/ocr/label.py#L67

**Comment by teolemon** [comment]
@segysego @raphael0202 here rather ?
https://github.com/openfoodfacts/robotoff/blob/master/robotoff/insights/ocr/packager_code.py#L47
We probably want it as a packager code

**Comment by segysego** [comment]
Hi @raphael0202 and @teolemon ,
I think I managed to get the feature working in local! However, I did not manage to push my branch to the Github repository.
Can you check that I have push permission?

**Comment by raphael0202** [comment]
I've invited you to join the organization.

**Comment by segysego** [comment]
Thank you @raphael0202 but I still cannot push my branch.

**Comment by raphael0202** [comment]
I also added you to the robotoff team. Does it work now?

**Comment by segysego** [comment]
Yes, it works, thank you

**Comment by raphael0202** [comment]
Done by @segysego, thank you!
