### ISSUE TITLE
Handle EMB codes that are lilke EMB dddddL

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/robotoff#137]
https://fr.openfoodfacts.org/codes-emballeurs?filter=EMB
Some packager codes have an extra letter, which the regex doesn't seem able to parse

https://github.com/openfoodfacts/robotoff/blob/abc4e695d69fea27b019a517b8ccb634ce35b2b8/robotoff/insights/ocr/packager_code.py#L26

```

EMB 56251E | 376
-- | --
EMB 72264 | 374

```

**Comment by segysego** [comment]
Hello, I checked the code and the regex seems to handle either 0 or 1 letter after the 5 digits.
The 2 samples you shared are matched by the current regex.
In the code, the extra letter is called the `company_code`.
Can you share an example where the regex does not match?
Thanks!
