### ISSUE TITLE
Regex improvement tracking

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/robotoff#14]
Weight:
`POIDS NET\nA L'EMBALLAGE\n200g`
Labels:
`Sans colorants ni conservateurs` (as is, Taxonomies will do the work)

**Comment by raphael0202** [comment]
@teolemon Isn't it better to add separately "sans colorants" and "sans conservateurs" ?

**Comment by raphael0202** [comment]
@teolemon done (e5534b488a988c23cc2c56fbf59d01384d7130c5)

**Comment by raphael0202** [comment]
I'm closing the issue, reopen it if there are other additions

**Comment by teolemon** [comment]
Taxonomies will auto add parents
