### ISSUE TITLE
Add link to API reference from Robotoff Doc

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/robotoff#1422]
### Problem
- Add link to API reference from Robotoff Doc so that lost developpers can find it by typing the keyword API
- https://openfoodfacts.github.io/robotoff/references/api/

### Part of
- #374

**Comment by raphael0202** [comment]
Actually it's already in the README, in:

```Robotoff can be used as...

    an [online API](https://openfoodfacts.github.io/robotoff/references/api/)
```

But we probably need a tutorial to introduce Robotoff API.

**Comment by teolemon** [comment]
@raphael0202 ![Image](https://github.com/user-attachments/assets/1ae8df5b-1b05-49a0-9b68-34067891e84b)
