### ISSUE TITLE
Save *all* insights in a new LatentProductInsight table

### ISSUE THREAD

**Issue by raphael0202** [openfoodfacts/robotoff#147]
Overview
---------

Currently, not all extracted insights are saved in the `ProductInsight` table. Indeed, some insights are dropped during importation, because:
- another insight with the same value was already imported for the product
- the value is already present for the product 
- another insight with a child value in the taxonomy was already imported for the product (label and category types)
- a child value in the taxonomy is already present for the product (label and category types)
- We found different values for the same field, in which case we drop all the insights
- the insight is considered invalid, either because it's impossible (ex: negative product weight), or the prediction is suspicious (ex: barcode not in brand barcode range).

These rules were added to guarantee high accuracy in predictions, and to allow automatic processing for most insights.
However, we lose valuable information by not storing all these insights. If these insights were all saved, here are a few features that could be implemented:
- detecting inconsistencies between the product field value and the predicted value (error detection).
- creating a new insight (=> robotoff question) if an insight was rejected (ex: product weight) and we have other detected product weights in store.
- generate better predictions by incorporating the information extracted from several images, instead of focusing on a single image

Proposal
---------

Create a new `LatentProductInsight` table, with the same columns (minu annotation-related ones).
In all `InsightImporter`s, import all insights in `LatentProductInsight` table.
Keep the insight importing mechanism unchanged.

**Comment by stephanegigandet** [comment]
I don't see any downside, except the potential volume it will generate. Would it be an issue?

**Comment by raphael0202** [comment]
It should be fine, as PostgreSQL is able to handle tables with millions of rows.

**Comment by teolemon** [comment]
What would be interesting is as much metadata on the processing methodology as possible so as to compute a `processing hash` 
OCR engine, date of OCR, date of `LatentProductInsight` generation. That way we can have concurrent LatentProductInsight and have reasoned ways to prefer one to another.

**Comment by raphael0202** [comment]
We save the date of LatentProductInsight during import. OCR engine is always Google Cloud Vision.
Concerning the date of the OCR, what information could it bring? If we reprocess image with a new OCR version, I plan to replace old latent insights with the new ones.

**Comment by raphael0202** [comment]
Done.
