### ISSUE TITLE
Incompatible requirements when running requirements_ml in addition to requirements

### ISSUE THREAD

**Issue by segysego** [openfoodfacts/robotoff#148]
**Describe the bug**
When installing all requirements in new environment python, I get a following message : "ERROR: tensorflow 2.0.1 has requirement wrapt>=1.11.1, but you'll have wrapt 1.10.11 which is incompatible."

**To Reproduce**
1. Create new virtual env with python 3.7.6
2. pip install -r requirements.txt
3. pip install -r requirements-dev.txt
4. pip install -r requirements_ml.txt
5. See error

**Expected behavior**
All packages installed without any error or warning

**Comment by raphael0202** [comment]
Thanks for reporting this issue, at which stage does the error occurs (requirements.txt, Dev or ml)?

**Comment by segysego** [comment]
It occurs after the third command: `pip install -r requirements_ml.txt`

**Comment by raphael0202** [comment]
Ok, only `requirements.txt` is required, the other requirements are to launch unit tests and to train models respectively. I will look into this issue, but it shouldn't be a problem for you to work on the project.

**Comment by raphael0202** [comment]
I'm closing this issue as we're now using poetry for dependency management.
