### ISSUE TITLE
prevent percentages over 100% in the OCR output

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/robotoff#149]
`%` seems interpreted as `9%` The user will of course spot it before validating, but we could try to be smart:
if percentage > 100 and last digit = 9 then remove last digit
![image](https://user-images.githubusercontent.com/1689815/76212369-98bcec80-6208-11ea-9648-41af76137777.png)
``` 689% fromage à pâte pressée non cuite (Maasdam) (lait* (Origine: UE) pasteurisé, sel, ferments lactiques, enzyme coagulante d'origine microbienne), 159% Emmental (lait (Origine: UE), 15% Mozzarella (lait (Origine : UE)), amidon de pomme de terre. *issu de vaches nourries sans OGM (<0,996). ``` 
https://world.openfoodfacts.org/product/4056489127352/rape-aux-3-fromages-auchan

**Comment by raphael0202** [comment]
I agree with Stéphane, the modification seems to risky to me. Better flag the product in a quality tag for manual inspection.

**Comment by teolemon** [comment]
Well, I can move it back to Product Opener for a new quality facet then
