### ISSUE TITLE
Create a `detected_languages` field

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/robotoff#150]
Create a `detected_languages` field for a product populated with the languages detected by Google in the OCR of images.
Create  a `detected_languages` field for each image of a product populated with the languages detected by Google in the OCR of this image.

detected_languages=fr,nl,de,it

That will enable us to compute things like:
- quality and edit opportunity facets
- detect images that are not stored in the right language

**Comment by raphael0202** [comment]
For each image, we now store in DB the associated language(s). What next steps do you consider?
