### ISSUE TITLE
Detect all languages present in a nutrition table

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/robotoff#151]
Detect all languages present in a nutrition table, and assign the image to all the languages present (eg French in addition to Dutch, or the reverse).

This should help us get more product multilingual, more quickly, as the app will then show a "Please take a Dutch ingredient picture" instead of the French picture.

**Comment by raphael0202** [comment]
Now nutrition image selection is in prod, we can consider it done. We decided to only select the nutrition image for the product main language to avoid redundant information (most products have a single multilingual nutrition table).
