### ISSUE TITLE
Test failing in local

### ISSUE THREAD

**Issue by segysego** [openfoodfacts/robotoff#157]
**Describe the bug**
All tests pass in local except one:
`tests/utils/test_i18n.py F`

**To Reproduce**
1. clone the project and install requirements in a virtual env
2. launch the tests with `python3 -m pytest tests`
3. See error

**Expected behavior**
All tests should pass.

**Comment by raphael0202** [comment]
The .po files must be compiled first: `cd i18n && bash compile.sh`.
This ensures that no error was introduced in the .po files.

**Comment by segysego** [comment]
Thank you @raphael0202 it worked!
