### ISSUE TITLE
Adding Label Rouge based on LogoAnnotations

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/robotoff#16]
```[{"logoAnnotations": [{"score": 0.93795, "mid": "/m/0kv95by", "boundingPoly": {"normalizedVertices": [{"y": 0.45687327, "x": 0.25254056}, {"y": 0.45687327, "x": 0.834747}, {"y": 0.7899458, "x": 0.834747}, {"y": 0.7899458, "x": 0.25254056}]}, "description": "label rouge"}]```
https://static.openfoodfacts.org/images/products/286/048/105/9045/1.json
https://static.openfoodfacts.org/images/products/286/048/105/9045/1.jpg

**Comment by raphael0202** [comment]
Done
