### ISSUE TITLE
Missing product image

### ISSUE THREAD

**Issue by hunsly** [openfoodfacts/robotoff#18]
Missing product image:
https://static.openfoodfacts.org/images/products/408/812/87/1.400.jpg

```json
{
	"questions": [{
		"barcode": "40881287",
		"type": "add-binary",
		"value": "Mcennedy",
		"question": "Does the product belong to this brand?",
		"insight_id": "2b3cb0da-8e1f-4265-be47-a96fee691000",
		"insight_type": "brand",
		"source_image_url": "https://static.openfoodfacts.org/images/products/408/812/87/1.400.jpg"
	}],
	"status": "found"
}
```

Good url: https://static.openfoodfacts.org/images/products/40881287/1.400.jpg

**Comment by teolemon** [comment]
Same issue here
![Capture d’écran 2019-04-08 à 11 34 06](https://user-images.githubusercontent.com/1689815/55715636-6f428200-59f5-11e9-92cc-fb12511f4ed0.png)
![Capture d’écran 2019-04-08 à 11 34 26](https://user-images.githubusercontent.com/1689815/55715637-6f428200-59f5-11e9-96e3-6ab2d42ae901.png)
![Capture d’écran 2019-04-08 à 11 34 53](https://user-images.githubusercontent.com/1689815/55715638-6fdb1880-59f5-11e9-92b8-069a0f0b00e4.png)

**Comment by raphael0202** [comment]
@teolemon Can you open a new issue for your bug? The cause is actually different.
@hunsly Fixed.
