### ISSUE TITLE
Extracting Label Rouge homologations

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/robotoff#202]
So I noticed that Label Rouge has its own packager code system. We could extract Label Rouge homologations.
https://hunger.openfoodfacts.org/logos?logo_id=552341
`Homologation n° LA 06/08` where `XX/XX`

It also almost always have: 
```
Décret du 5/01/07 
Décret du 05/01/07
Décret du 5.01.07 
Décret du 05.01.07
```
So we could infer Label Rouge whenever we see that text
![image](https://user-images.githubusercontent.com/1689815/84508449-97490780-acc2-11ea-9f22-bc9ac2943f16.png)
![image](https://user-images.githubusercontent.com/1689815/84508470-9f08ac00-acc2-11ea-9a19-6dc4f8096a6c.png)

**Comment by raphael0202** [comment]
Solved in 38e7acf561ca9126de2ce864d2a4b5d0a720b98b.
