### ISSUE TITLE
Support multi packaging

### ISSUE THREAD

**Issue by hangy** [openfoodfacts/robotoff#21]
There's some products that contain multiple items. The quantity is often printed as "2 x 100 g" on the packaging. Currently robotoff drops the "2 x" prefix and asks the user if "100 g" is the correct weight. A better option might be to keep the prefix, and possibly add the [multipack](https://world.openfoodfacts.org/packaging/multipack) label when "2 x 100g" is confirmed by the user.

**Comment by raphael0202** [comment]
Good idea :+1:

**Comment by raphael0202** [comment]
Done (dca12d8480cd2abc5cb78196848004cb512eb38c)
