### ISSUE TITLE
Extract serving size recommendations from some nutrition table images

### ISSUE THREAD

**Issue by CloCkWeRX** [openfoodfacts/robotoff#218]
While extracting full nutrition tables may not be easy, many do feature a serving size label.

Similar to extracting a general quantity, from images identified as nutrition tables; consider looking for 
"Serving size 25g" (Australian labels)
"Serving size 125ml" (Australian labels)
"Serving size 2/3 cup (55g)" (Us labels)

I'm not sure about other labelling standards.

**Comment by teolemon** [comment]
Related to #98

**Comment by raphael0202** [comment]
It's actually exactly the same issue as #98. Do you mind merging the two issues?

**Comment by CloCkWeRX** [comment]
Ah, my bad, missed that through use of different terms. Works for me.
