### ISSUE TITLE
Update conflict after product edited

### ISSUE THREAD

**Issue by hangy** [openfoodfacts/robotoff#23]
Sometimes, the roboto-app user overwrites previously user-provided information.

1. In [revision 5](https://world.openfoodfacts.org/product/20090753/puten-lachsschinken-dulano?rev=5), I uploaded a picture that has contains the product's quantity.
2. In [revision 8](https://world.openfoodfacts.org/product/20090753/puten-lachsschinken-dulano?rev=8), I filled several product facts, including `quantity`.
3. In [revision 9](https://world.openfoodfacts.org/product/20090753/puten-lachsschinken-dulano?rev=9), robotoff overwrites the correct quantity value, removing the [℮ sign](https://github.com/openfoodfacts/robotoff/issues/20#issue-430117720)

This is probably an update conflict caused by robotoff processing the image OCR result while I was entering the basic product information. Note that this is not a split-second difference, as there's several minutes between both edits. In this case, the update conflict could be avoided if robotoff would first retrieve the product before (over-)writing the content that was added after it started processing the OCR.

**Comment by raphael0202** [comment]
Fixed in 8155746026da7809171e4f3e06502877bde2f398.

**Comment by raphael0202** [comment]
There is a check for all types of insights, but the check was bugged (we sent the update only if `quantity` was filled, which is the exact opposite of what we want).
There is a delay of 10 minutes between the insight extraction and the annotation (=update), to be sure that the contributor will not send additional information.
