### ISSUE TITLE
Detecting labels in product names

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/robotoff#230]
I can't remember if we do it already, but detecting labels in product names and proposing them as questions or applying them automatically would be great.
https://world.openfoodfacts.org/product/3250392939465/rosette-label-rouge

**Comment by deepaksirohiwal** [comment]
Hi @teolemon, does this issue requires label extraction using OCR?

**Comment by alexgarel** [comment]
@deepaksirohiwal I don't think so, it's simply about searching text in another piece of text. @raphael0202 released a PR last month where we match categories in product names. But I imagine that it would be simpler here, just matching existing labels (and synonyms) in product_name field (we generally use flashtext for that)

**Comment by raphael0202** [comment]
We do it already: https://github.com/openfoodfacts/robotoff/blob/9464f46df11542d42a0987666506a90fc9f367d3/robotoff/insights/extraction.py#L99
