### ISSUE TITLE
Robotoff displays untaxonomized category names

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/robotoff#241]
### What
Robotoff is serving untaxonomized category names. It seems like a behaviour change.

### Screenshot
![image](https://user-images.githubusercontent.com/1689815/91646718-80f55100-ea52-11ea-887f-f3850ce9d3bc.png)

**Comment by teolemon** [comment]
https://github.com/openfoodfacts/robotoff/issues/308 is a duplicate of this

**Comment by raphael0202** [comment]
We display untaxonomized value when:
- the value does not exist (anymore) in the taxonomy
- there is no translation of the taxonomized value in the target language

Did you reproduce this issue recently?
