### ISSUE TITLE
Add support for writing to the new packaging field

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/robotoff#257]
### What
Add support for writing to the new packaging field which is now live.
https://world.openfoodfacts.org/product/3560070820306/fingers-de-poulet-carrefour
API-wise, that's an exact replica of the ingredients fields, with the same bevaviour, the same ability to OCR the field.

- [ ] Add write support for the field to the Robotoff backend.
- [ ] Adapt REGEX to extract the full instruction instructions as opposed to the partial extraction we do now.
- [ ] Apply automatically

### Part of
- #121

**Comment by raphael0202** [comment]
I'm closing this issue, as we now have the new `packagings` field (API v3).
