### ISSUE TITLE
Broken images (sometimes)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/robotoff#26]
![Capture d’écran 2019-04-08 à 11 34 06](https://user-images.githubusercontent.com/1689815/55718660-8173ee80-59fc-11e9-90f6-9a650968b371.png)
![Capture d’écran 2019-04-08 à 11 34 26](https://user-images.githubusercontent.com/1689815/55718661-8173ee80-59fc-11e9-9140-cf0590870a31.png)
![Capture d’écran 2019-04-08 à 11 34 53](https://user-images.githubusercontent.com/1689815/55718662-8173ee80-59fc-11e9-9e35-02ca6526d793.png)

**Comment by raphael0202** [comment]
For the 1st product you mentioned, the JSON exists (https://static.openfoodfacts.org/images/products/347/882/002/3641/front.3.full.json), but not the original image.
The JSON probably comes from the OCR dumps.

**Comment by hangy** [comment]
Another weird case:
- Product url: https://de.openfoodfacts.org/product/20183530
- Bad image url displayed by robotoff: https://static.openfoodfacts.org/images/products/20183530/ingredients_de.7.full.jpg.google_cloud_vision.jpg
- insight_id: c8f7c0a9-9550-4047-90e7-de7979d90c66

**Comment by raphael0202** [comment]
Closing this issue, as we now shouldn't have broken images in production. Feel free to reopen if needed.
