### ISSUE TITLE
Be more precise in date extraction

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/robotoff#27]
DLUO, Date Limite d'Utilisation Optimale
DLC, Date Limite de Consommation
DDM, Date de durabilité minimale

A consommer avant
A consommer de préférence avant

**Comment by teolemon** [comment]
cc @stephanegigandet

**Comment by stephanegigandet** [comment]
It's not really about date extraction, more about extracting conservation indications, for which we need a new field. e.g. a new conservation tag field, with a new taxonomy for conservation conditions. And then we have that, we can use robotoff to populate it.

**Comment by raphael0202** [comment]
I'm closing the issue until OFF supports it.
