### ISSUE TITLE
Provide some context about the perimeter of the category in the API

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/robotoff#270]
### Why
When answering questions on categories, I am often lost: I have no idea whether a product should belong to a certain category. I do not know what the category should comprise. So I answer "unknown".

### Solution
Either make the category names longer, or add a description, so that it is easier to decide whether a product belongs to a certain category.

### Alternatives
I could look at other categories to see what products are in it, but that is to much work.

**Comment by alexgarel** [comment]
I propose the second solution for [hunger-game](https://github.com/openfoodfacts/openfoodfacts-hungergames/issues/405) but I agree this should be different for questions in the app.

**Comment by raphael0202** [comment]
This is more hunger-games related. Category descriptions are in the pipeline for Hunger Games.
