### ISSUE TITLE
Add links to high res images in the api.

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/robotoff#271]
**Is your feature request related to a problem? Please describe.**
Add also a link to the original image (id) in the json. Often the current image has a to low resolution to be able to answer a question: it is unreadable.

**Describe the solution you'd like**
I tried to decode the image id from the provided image url, but that is not possible.

**Comment by raphael0202** [comment]
Now we only store raw images (1.jpg, 2.jpg) in the insight `source_image` field.
