### ISSUE TITLE
Start instruction incomplete?

### ISSUE THREAD

**Issue by hangy** [openfoodfacts/robotoff#28]
According to https://github.com/openfoodfacts/robotoff/blob/b7435bc5558169a6b0e95e2f7114e1a4e42605ac/README.md#installation, it should be possible to start everything with `docker-compose up`, however the `api-dataset` volume is declared as an external module: https://github.com/openfoodfacts/robotoff/blob/2d463dca91ba521823034567f10f58bc71ca772a/docker-compose.yml#L46-L48
Does this need to be mounted anywhere special? What's the reason for it to be declared `external`? 🙂

**Comment by hangy** [comment]
Also, the Dockerfile tries to copy a non-existing directory `models` to the container? https://github.com/openfoodfacts/robotoff/blob/b1225a3d3d7b88e729a3289cf74b0bd09aaaad2f/Dockerfile#L8

**Comment by raphael0202** [comment]
No there are no reason to mark the volume as external, just a bad habbit ;). And the models directory currently contains all machine learning models. These models are currently stored on my computer, I will add an issue to find a way to make them easily downloadable.
I've fixed both issues.

**Comment by hangy** [comment]
Thank you :)
