### ISSUE TITLE
Integrate TableNet into Robotoff

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/robotoff#299]
Tablenet

### Code
https://github.com/openfoodfacts/openfoodfacts-ai/tree/master/nutrition-table-extraction/models_test/TableNet 

- [ ] needs requirements.txt
- [ ] Latest commit by Sadok needs to be pushed
- [ ] Integrate as an on-demand API first, and prepare Robotoff for batch processing
### Parameters that should be tweakable from url
image url
bounding boxes : x1, y1, x2, y2
threshold:
step:

### Part of
- #372

**Comment by raphael0202** [comment]
As we need further work on nutrition table extraction before integration, I'm closing this issue.
