### ISSUE TITLE
Weight detection upper than 3000 g

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/robotoff#302]
**Describe the bug**
` Does this weight match the weight displayed on the product? 760094310634 g `

Weight detection shouldn't detect values upper than, say, 10000 g -- or even 3000 g.

**To Reproduce**
https://world.openfoodfacts.org/product/3760094310634/mes-p-tites-cereales-bio-aline-olivier
![image](https://user-images.githubusercontent.com/562352/102594602-b19eea80-4116-11eb-8c88-cfcb568c17a3.png)

**Expected behavior**
No detection at all.

**Comment by Gaurav7888** [comment]
For this I should look at which file ? @CharlesNepote

**Comment by CharlesNepote** [comment]
@Gaurav7888 I really don't know, I'm just a user... Try to ask in our #robotoff Slack channel.

**Comment by Gaurav7888** [comment]
@alexgarel Okay alex I will try to write test first, Thanks!!

**Comment by teolemon** [comment]
We already have a function for that @alexgarel @CharlesNepote @Gaurav7888 : 
https://github.com/openfoodfacts/robotoff/blob/4ee6474223e33cb7fb2ace8ec13e66677336cdf6/robotoff/prediction/ocr/product_weight.py#L89
Further investigation is thus needed (is it still happening, what de we do when a suspect weight is detected,…)

**Comment by alexgarel** [comment]
yep writing a test is still the right way to go.

**Comment by raphael0202** [comment]
I checked, we generate the insight but don't apply it automatically when weight is suspisciouly high.
Now we don't generate the insight at all. I've also added some tests.
Solved in https://github.com/openfoodfacts/robotoff/commit/51a19fa46efdb238d0eedfa69b7540f0a1333984
