### ISSUE TITLE
Be more flexible for category predictions

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/robotoff#31]
Ignore the following in category detection:

- Remove some keywords
`Bio…`
- Remove numbers
- Remove quantities `230g, GR230, 230GR,75cl`
- Remove all labels from the taxonomy
`Bio, IGP, PGI, AOC…`
- Remove Whitelisted brands (or all brands from the taxonomy)
- Don't be sensitive to capslock/accentuation
- Leverage taxonomy synonyms
- Allow a distance
`Donut Chocolat`
`Donnut`
`2 bavettes daloyau`

**Comment by raphael0202** [comment]
There is already a preprocessing pipeline, integrated in the search engine, which includes:
- lowercasing, accent stripping
- removal of numbers
- removal of stop words (language specific)

I've added a preprocessing step on the client side (before sending the request to the search engine), removing weights and keywords (including labels).
Before removing brands, we have to make sure the brand name is not a word that may be part of a category name.

**Comment by raphael0202** [comment]
@teolemon Now the new category prediction model is on production, I guess we can close this issue?

**Comment by teolemon** [comment]
yes
