### ISSUE TITLE
Hunger Games broken?

### ISSUE THREAD

**Issue by jolesh** [openfoodfacts/robotoff#310]
When I open https://hunger.openfoodfacts.org the page loads but it is loading forever to find products. I tried Firefox and Chrome on Linux Mint 20
![Untitled](https://user-images.githubusercontent.com/29330125/104482428-36bad980-55c7-11eb-86a5-cf0c0135e7ff.png)

**Comment by teolemon** [comment]
This should be fixed the deployment I made yesterday (modulo general slowness)

**Comment by jolesh** [comment]
@teolemon Thanks, you did solve it :+1:
