### ISSUE TITLE
(Hypothesis) PeeWee random might be slowing down Hunger Games queries

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/robotoff#314]
The hypothesis was formulated that PeeWee's random func might be slowing down Hunger Games queries.

**Comment by kulizhsy** [comment]
Just for my own understanding: is the issue here the fact that we have a randomisation mechanism (randomising large volumes of data is never going to be cheap) or randomisation cost is fine in theory, but we assume something is particularly bad with the PeeWee's implementation?

**Comment by kulizhsy** [comment]
Trying to understand the latency difference:

```
import requests
import statistics

latencies = []
for iter in range(100):
    response = requests.get("https://robotoff.openfoodfacts.org/api/v1/images/predictions?count=10&random=true")
    if response.status_code == 200:
        latencies.append(response.elapsed.total_seconds())
    
print("mean latency: %f" % statistics.mean(latencies))
print("quantiles: %r" % statistics.quantiles(latencies))
```

gives:

```
mean latency: 5.857252
quantiles: [5.69207125, 5.749179, 5.92697825]
```

In comparison, 'random=false' is:

```
mean latency: 0.159654
quantiles: [0.11610025, 0.1246395, 0.1289835]
```

Varying the 'count' parameter doesn't have any impact on the latency distribution.


The question I now have is the following:
What is the use case for fetching random sets of insights (i.e. how truly random do they have to be/ what is the range for the 'count' parameter do we typically expect when we want random results)?

The best option I see for now is to try to optimise the Postgres query that gets executed such that it's cheaper to randomise the order.

**Comment by teolemon** [comment]
We use it to show Random Questions in Hunger Games: https://github.com/openfoodfacts/openfoodfacts-hungergames/blob/f90e0df3c51aaadb804d35653fabd4a814ec2bb3/src/views/QuestionView.vue#L321

http://hunger.openfoodfacts.org/

It probably does not have to be random, and the issue is far less problematic because we moved Robotoff to a dedicated VM.

**Comment by kulizhsy** [comment]
I see - if there's no action to be taken on this issue, can it be considered resolved or is there anything outstanding left?

**Comment by raphael0202** [comment]
I think I added randomization to prevent two Hunger Games contributors from receiving the same insight batch

**Comment by kulizhsy** [comment]
Closing this, since there seems nothing outstanding on this issue.
