### ISSUE TITLE
Wrong detection on weight

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/robotoff#32]
https://world.openfoodfacts.org/images/products/304/636/900/8889/1.json

https://world.openfoodfacts.org/images/products/304/636/900/8889/1.jpg

https://world.openfoodfacts.org/product/3046369008889

` 125ge\n90g ` vs `Nettogewicht\n7.0g`

**Comment by stephanegigandet** [comment]
For quantities in grams, any number with a comma/dot is probably not a quantity. e.g. 3.7g : https://world.openfoodfacts.org/product/5016599008896

**Comment by raphael0202** [comment]
Done (74cd42a24ce540c2639543c6d42a0fe2541110b0)
For the issue raised by @teolemon, there isn't much to do, as is is due to an incorrect paragraph detection by Google Cloud Vision (unless developing our own algorithm)
