### ISSUE TITLE
Get rid of some domain hardcodes

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/robotoff#335]
- [ ] Get rid of some domain hardcodes
- [ ] https://github.com/openfoodfacts/robotoff/blob/837c2da66b80e48a47788dc92d7975bd6c569424/robotoff/cli/annotate.py#L15
- [ ] https://github.com/openfoodfacts/robotoff/blob/837c2da66b80e48a47788dc92d7975bd6c569424/robotoff/cli/annotate.py#L19
- [ ] https://github.com/openfoodfacts/robotoff/blob/837c2da66b80e48a47788dc92d7975bd6c569424/robotoff/workers/tasks/update_recycle.py#L59
- [ ] https://github.com/openfoodfacts/robotoff/blob/837c2da66b80e48a47788dc92d7975bd6c569424/robotoff/workers/tasks/update_recycle.py#L131
- [ ] https://github.com/openfoodfacts/robotoff/blob/837c2da66b80e48a47788dc92d7975bd6c569424/robotoff/logos.py#L46
- [ ] https://github.com/openfoodfacts/robotoff/blob/837c2da66b80e48a47788dc92d7975bd6c569424/robotoff/logos.py#L69
- [ ] https://github.com/openfoodfacts/robotoff/blob/837c2da66b80e48a47788dc92d7975bd6c569424/robotoff/cli/spellcheck.py#L27
- [ ] https://github.com/openfoodfacts/robotoff/blob/837c2da66b80e48a47788dc92d7975bd6c569424/robotoff/cli/spellcheck.py#L68
- [ ] https://github.com/openfoodfacts/robotoff/blob/837c2da66b80e48a47788dc92d7975bd6c569424/robotoff/metrics.py#L77
- [ ] https://github.com/openfoodfacts/robotoff/blob/837c2da66b80e48a47788dc92d7975bd6c569424/robotoff/metrics.py#L125
- [ ] https://github.com/openfoodfacts/robotoff/blob/5bfd84155a995f845856805a8c47ba8caa5a7875/robotoff/cli/batch.py#L50
- [ ] https://github.com/openfoodfacts/robotoff/blob/6415d6ca30cc66d801d2ffc3879bbc12f60303fd/robotoff/slack.py#L92
- [ ] https://github.com/openfoodfacts/robotoff/blob/837c2da66b80e48a47788dc92d7975bd6c569424/robotoff/insights/ocr/core.py#L44
- [ ] https://github.com/openfoodfacts/robotoff/blob/5bfd84155a995f845856805a8c47ba8caa5a7875/robotoff/models.py#L149
- [ ] https://github.com/openfoodfacts/robotoff/blob/837c2da66b80e48a47788dc92d7975bd6c569424/robotoff/insights/question.py#L18
- [ ] https://github.com/openfoodfacts/robotoff/blob/5bfd84155a995f845856805a8c47ba8caa5a7875/robotoff/off.py#L69

**Comment by kulizhsy** [comment]
Correct me if I'm wrong, but I don't believe we need to modify the hardcoded 'cli' paths.

If somebody wants to test the cli, they would just run the binary locally - repointing it to talk to Robotoff 'dev' would actually decrease the testability, since there's going to be less production-like data there to play with.
