### ISSUE TITLE
robotoff-cli download-models is fixed to a particular release path

### ISSUE THREAD

**Issue by kulizhsy** [openfoodfacts/robotoff#338]
### What
Currently robotoff-cli will fetch the models from:

https://github.com/openfoodfacts/robotoff-models/releases/download/category-predictor-ocr-lewagon-1.0/bestridge_compressed.joblib

Once we have a story for unified model releases this hardcode should be fixed.

### Part of
- #MLOps

**Comment by raphael0202** [comment]
`robotoff-cli download-model` doesn't exist anymore, as we're now using `make dl-models`
