### ISSUE TITLE
Two different Nutri-Score at the same time

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/robotoff#355]
For the following product, robotoff has applied two different Nutri-Score detections at the same time:
* Nutri-Score E: https://world.openfoodfacts.org/product/3760139470880/20-dont-4-oeufs-offerts-avibresse-dates-du-jour-de-ponte?rev=8
* Nutri-Score A: https://world.openfoodfacts.org/product/3760139470880/20-dont-4-oeufs-offerts-avibresse-dates-du-jour-de-ponte?rev=9

**Comment by teolemon** [comment]
@CharlesNepote Your issue will be solved by solving: https://github.com/openfoodfacts/robotoff/issues/138

**Comment by teolemon** [comment]
Also a duplicate of : https://github.com/openfoodfacts/robotoff/issues/115

**Comment by alexgarel** [comment]
@teolemon why should we filter that. Those are only insight, we don't know which one is right, and it's up to a human to decide. How can we decide without one ?

**Comment by alexgarel** [comment]
I close it as it does not seems like a real problem. (It's up to human to decide, moreover some products have more than one score).
