### ISSUE TITLE
Reconnect Grafana+InfluxDB to Robotoff

### ISSUE THREAD

**Issue by kulizhsy** [openfoodfacts/robotoff#363]
Robotoff exports [metrics](https://github.com/openfoodfacts/robotoff/blob/525439238bd74fcca1b24f94f0b82b97dd80edde/robotoff/scheduler/__init__.py#L260) daily to InfluxDB which is then served via Grafana, on [monitoring.openfoodfacts.org](monitoring.openfoodfacts.org).

This has been broken for a few months now, since Robotoff was migrated to its own VM.

A new instance of Grafana+InfluxDB should be created:

1. Old InfluxDB/Grafana data still lives on off2.free.org, under /srv2/docker/docker/volumes which should be migrated once the new Grafana instance is running.
2. [These settings](https://github.com/openfoodfacts/robotoff/blob/525439238bd74fcca1b24f94f0b82b97dd80edde/robotoff/settings.py#L222) need to be updated to point to the new InfluxDB location.

**Comment by kulizhsy** [comment]
The original docker-compose.yml files can be found on off2:

```
kulizhsy@off2:/home/docker$ ls
docker  grafana  influx
```

**Comment by kulizhsy** [comment]
Actually looking at the [metrics implementation](https://github.com/openfoodfacts/robotoff/blob/49fb31df756bf28abc757a6c3f1ca6fbd8adba7a/robotoff/metrics.py#L95) there doesn't seem anything Robotoff-specific there - all of the metrics come from Product Opener.

@ocervell if you're planning to migrate PO's cron jobs to Github actions, this could also be migrated and removed from Robotoff

**Comment by teolemon** [comment]
- [ ] https://github.com/openfoodfacts/openfoodfacts-infrastructure/issues/49
- [ ] https://github.com/openfoodfacts/openfoodfacts-infrastructure/issues/50

**Comment by ocervell** [comment]
@teolemon  do we need a separate VM for monitoring tools, or is there an existing one ?

**Comment by teolemon** [comment]
https://github.com/openfoodfacts/openfoodfacts-monitoring exists

**Comment by ocervell** [comment]
Taking care of this in openfoodfacts-monitoring repo
