### ISSUE TITLE
/api/v1/dump does not work

### ISSUE THREAD

**Issue by kulizhsy** [openfoodfacts/robotoff#365]
### What
https://robotoff.openfoodfacts.org/api/v1/dump throws a 502, while restricting the dump params to a single insight type works, e.g. https://robotoff.openfoodfacts.org/api/v1/dump?insight_types=store

Perhaps this has something to do with the size of the dataset?

### Part of
- #Bugs

**Comment by kulizhsy** [comment]
The most probable cause for the timeouts is the fact that the postgres dump from Feb 2021 is >8gbs in size

**Comment by raphael0202** [comment]
The dump method works as expected, but indeed the query takes too much time to be processed, which leads to a server timeout. We should probably ask for stricter criteria to avoid such timeouts, first in the documentation.

**Comment by raphael0202** [comment]
I added an upper limit of 10k on the number of insights that can be dumped
