### ISSUE TITLE
Unify the TF model serving path

### ISSUE THREAD

**Issue by kulizhsy** [openfoodfacts/robotoff#380]
### What
Currently most of the existing TF models are being served through the TF serving container reading models from `tf_models/`.
The only exception for this is the category classifier model with is read directly by Robotoff from `models/`.

Moving the category classifier to being served via the TF Serving would allow us to add the retraining component to the models more easily.

### Part of
- #MLOps

**Comment by raphael0202** [comment]
I'm closing this issue, as it's no longer relevant (we moved away from TF Serving to Triton)
