### ISSUE TITLE
Nutrition Table-releated insights are not being generated

### ISSUE THREAD

**Issue by kulizhsy** [openfoodfacts/robotoff#381]
### What
There have been no insights of type `nutrition_table_structure`, `nutrition_image`, etc. in 2021.

It seems that TF serving is configured correctly to serve these models - this issue tracks the investigation efforts into why we have no new insights of this type.

**Comment by kulizhsy** [comment]
My findings so far:

There is a TF model called [`nutrition-table`](https://github.com/openfoodfacts/robotoff/blob/dcc4b52e19abb7743f647a7464e5577997bbc1e7/robotoff/settings.py#L204) is working and is served by the TF Serving container:

https://robotoff.openfoodfacts.net/api/v1/images/predict?image_url=https://world.openfoodfacts.org/images/products/317/568/001/1480/nutrition_fr.166.full.jpg&models=nutrition-table

However, we[ don't actually trigger it](https://github.com/openfoodfacts/robotoff/blob/4dd40b1f3bdbfc28a8f10cfec06d489477087580/robotoff/insights/extraction.py#L274) on the 'predict_objects' calls.


**QUESTION 1**:  Should we trigger it?

**QUESTION 2**: I think this would generate a 'label' insight with `nutrition-table` as the label value?

This doesn't really help with the question of why we are not generating any insights of type `nutrition_image`, `nutrition_table_structure`, etc.


@raphael0202 introduced all of the `nutrition_table_structure`-related code in [this commit].(https://github.com/openfoodfacts/robotoff/commit/dcbf1fbd008b8ebed0db19fd3b434dedc7e48cf2)


**QUESTIONS 3,4,5**: Are these two insights related somehow? I.e. we first detect that the image has a nutrition table, then piggy-back the other insights generation? If, so how?

**QUESTION 6**: Where does nutritional information(e.g. image on [this product](https://world.openfoodfacts.org/product/3175680011480/biscuit-sesame-gerble)) currently come from?

cc @teolemon

**Comment by raphael0202** [comment]
We now store nutrition table predictions in `image_prediction` table
