### ISSUE TITLE
Clean up non-actionable check failures on PRs

### ISSUE THREAD

**Issue by kulizhsy** [openfoodfacts/robotoff#390]
These failures don't indicate that there's anything wrong with the submitted code. Instead they're spammy and train the contributors to ignore any PR failure.

Example of such failures:

-SonarCloud coverage error (misconfigured, coverage is already covered by a different check).
-Code quality & test checks double trigger on a merge - one of them errors out.
- Crowdin trigger (and fail?) on unrelated changes

**Comment by teolemon** [comment]
Crowdin: I'll change the trigger to only the robotoff.po file.

**Comment by kulizhsy** [comment]
Thanks @teolemon

**Comment by kulizhsy** [comment]
+ also move the documentation generation to a separate action, rather than it being the last step in the 'Code quality checks'
