### ISSUE TITLE
Stabilise Existing ML Models

### ISSUE THREAD

**Issue by kulizhsy** [openfoodfacts/robotoff#394]
### What
- [ ] Thorough documentation of currently-integrated ML models (training dataset/ TF version/etc.), already [started](https://docs.google.com/spreadsheets/d/1p2tvA5ySm0RJpTjUwT3fFrDJNJLXNlVTkxxU-izTIMA) by @teolemon
- [ ] Be able to run all of the training code for all of the existing models
- [ ] Validate the models are fully working
  - [ ] nutrition_table is not working correctly
  - [ ] automatic application is broken for some insight types
### Part of
- #MLOps

**Comment by raphael0202** [comment]
nutrition table model is working again, and models are now well documented.
