### ISSUE TITLE
Detect brands in product name

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/robotoff#42]
Detect brands in product name
Many times, brands are concatenated in product names

**Comment by teolemon** [comment]
An example in the wild:
![image](https://user-images.githubusercontent.com/1689815/69902263-b669f280-138b-11ea-9124-cf9f7abae0f4.png)

**Comment by teolemon** [comment]
@raphael0202 an extension for brands.

**Comment by raphael0202** [comment]
Done.
