### ISSUE TITLE
Add checks for quantities

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/robotoff#43]
Quantity: 0225 kg 
- any quantity above 10 kg is very likely wrong, and any quantity above 2000g that is not round (e.g. 2131g) has higher chances of being incorrect.
- quantities that begin with 0 without a . or , after are incorrect

14,90 kg  recognized instead of 14,90 €/kg -> not sure what the regexp is, did we have €/ in the OCR and the regexp ignored it?

**Comment by Lunique** [comment]
I just found some drinks that had ".33 l" in the quantity field which read as 33 l instead of 0,33 l (or 330 ml)

**Comment by raphael0202** [comment]
@Lunique The weight is currently not detected from images OCR if there is a space after the comma, no there is currently no risk on this side.

**Comment by raphael0202** [comment]
@stephanegigandet 
In your last example, the euro symbol was not present in the OCR text: `Poids net\n14,90kg`.
Above the 10 kg limit, we can disable the automatic annotation. I agree with you on the remaining points. 

Below are the links to the products mentioned:
- https://fr.openfoodfacts.org/produit/2273694012002/jambon-superieur-sans-couenne (14,90 kg)
- https://fr.openfoodfacts.org/produit/0214599018371/chouquette (0225 kg)

**Comment by raphael0202** [comment]
Done in (fc23d8810e46e70759d39bd3aecc8fe1ca07d2fb, 66129dd67947059707bc3b2f4300925a608382d2)

**Comment by raphael0202** [comment]
@stephanegigandet `any quantity above 10 kg is very likely wrong, and any quantity above 2000g that is not round (e.g. 2131g) has higher chances of being incorrect.` -> for these 2 cases, i don't discard the insight bu disable automatic annotation

**Comment by Lunique** [comment]
@raphael0202 I only checked products on off listed under the quantity section as "Product-quantity-over-10kg" as stephane asked to tell about possible patterns to find these mistakes. I don't use or have experience with OCR maybe those quantities were added by users by hand.

@stephanegigandet I had one product with 12 kg where the size was right but it wasn't a food object I moved it to opf https://de.openproductsfacts.org/produkt/4000602008905/galarkor-f8-dr-becher don't know if this is of interested too
