### ISSUE TITLE
Doc Gen seems broken because of a broken virtualenv

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/robotoff#437]
Run bash ./build_mkdocs.sh
The virtual environment found in /home/runner/work/robotoff/robotoff/.venv seems to be broken.
Recreating virtualenv robotoff in /home/runner/work/robotoff/robotoff/.venv
typer: unknown option --name
Error: Process completed with exit code 1.

**Comment by ocervell** [comment]
It's broken only on Python 3.7, the build for 3.8 works https://github.com/openfoodfacts/robotoff/runs/3608357299?check_suite_focus=true

**Comment by ocervell** [comment]
This is the command that fails on 3.7:

```
poetry run typer robotoff/cli/main.py utils docs --name robotoff-cli --output $cli_md
```

**Comment by kulizhsy** [comment]
Ee should just remove the 3.7 - there's no need to generate the docs with 2 python versions. I'll send a PR
