### ISSUE TITLE
Robotoff should update products on the server domain that called it (OFF or OBF, prod or dev)

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/robotoff#47]
OFF sends a server_domain variable when it pings robotoff, which can be openfoodfacts.org , dev.openfoodfacts.org, openbeautyfacts.org etc. 

Robotoff should store the server domain so that it can applies its insights to the same server that called it.

**Comment by raphael0202** [comment]
I've started to work on this issue (see 8238fa302a4f393dfb6868b525dca44ddb5ea19a).
As it is a pretty big change (every SQL query related to product insights is impacted), the development will be progressive on this issue.

**Comment by raphael0202** [comment]
Done in #1083 and #1084.
