### ISSUE TITLE
Docker Robotoff build is too slow

### ISSUE THREAD

**Issue by ocervell** [openfoodfacts/robotoff#482]
The commit https://github.com/openfoodfacts/robotoff/commit/ea720a7e7cda22307411e7eaf019fef02bd7c024 introduced a change in the Dockerfile that will force rebuilding the container on any code change (`chown off:off` line 50).

**Comment by alexgarel** [comment]
@ocervell I guess I should instead use the `--chown=off:off` option on COPY.
