### ISSUE TITLE
Categories : allow to choose a category or sort categories

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/robotoff#49]
The product category is VERY important in Open Food Facts: no category means no Nutri-Score!

Some categories are very easy to validate (example: `Baies de goji séchées`).

If we can choose the category name (example: &category=Gressins), it would allow validating multiple products at a time (see how mass editor is working). UI will have to be built, I know.

For Hunger Game, we could also have categories sorted by alpha: it's easier to validate X consecutive products of the same category than changing the category for each new picture.

**Comment by teolemon** [comment]
already done backend side. I have filed a bug on the frontend: https://github.com/openfoodfacts/openfoodfacts-hungergames/issues/12

**Comment by raphael0202** [comment]
As it is a front-end issue, I'm closing this ticket
