### ISSUE TITLE
Miniatures (and then notif) broken in the #robotoff-alerts-annotations notifications

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/robotoff#495]
Miniatures broken in the #robotoff-alerts-annotations notifications. It started on September 16th. We got no notifications at all anymore shortly thereafter.
```
 
Prediction for <https://<robotoff.settings.BaseURLProvider object at 0x7fb0642abed0>/api/v1/images/crop?image_url=https://static.openfoodfacts.org/images/products/842/258/405/8031/5.jpg&y_min=0.509062409&x_min=0.557891786&y_max=0.601774395&x_max=0.764172375%7Cimage> (annotate logo, product):
UNKNOWN - None: 0.71
packager_code - None: 0.21
brand - Marcel Petite: 0.05
label - en:palm-oil-free: 0.01
brand - Buitoni: 0.0099
label - en:usda-organic: 0.0099
``` 

![image](https://user-images.githubusercontent.com/1689815/142617743-95e9c5df-d870-4d1f-9dd4-921edb8adc67.png)

**Comment by kulizhsy** [comment]
16th of September was the last release to production - looking into what could be causing the lack of notifications.

**Comment by kulizhsy** [comment]
We are still generating the logo insights, seems that it's just the reporting that's broken:

```
postgres=# select count(*) from product_insight where timestamp > '2021-09-11' and type='label' and automatic_processing and predictor='universal-logo-detector';
 count 
-------
   112
(1 row)
```

**Comment by teolemon** [comment]
For some reason, it's broken again after the last deploy @alexgarel

**Comment by alexgarel** [comment]
@teolemon it's fix isn't it ?

**Comment by teolemon** [comment]
Probably, closing
