### ISSUE TITLE
Detect product weights from image OCR 

### ISSUE THREAD

**Issue by raphael0202** [openfoodfacts/robotoff#5]
We're already extracting product weight from image OCRs : https://github.com/openfoodfacts/robotoff/blob/master/robotoff/insights/ocr.py#L351

However, the extracted candidates are not necessarily the product weight, but can come from the nutritional table.

**Comment by teolemon** [comment]
Typically, we have values < 100 g (typically nutrition, but may be actual weight on products that weight less than 100g), values < 100 g (could be nutrition per portion on a very large portion)
We also have poids, poids net égoutté.

**Comment by teolemon** [comment]
Using weight mentions and unit could be a good sandwich detector:
```
WEIGHT_MENTIONS = (
    "poids net:",
    "poids net égoutté:",
    "net weight:",
    "peso neto:",
    "peso liquido:",
    "netto gewicht:",
)
```
