### ISSUE TITLE
Index based predictions should avoid serving requests while building

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/robotoff#504]
**Describe the bug**

Currently, `ElasticsearchExporter.export_index_data` does first delete objects from the index, then refill it.
In the mean time we could have request for categorization or ingredient spellchecking arriving, which will be answered erroneously.

**To Reproduce**

(not easy to reproduce as it involves a time sync)

1. launch ElasticsearchExporter.export_index_data from a shell
2. Ask for categorization, at the point when index is quite empty
3. See no category predicted (or not all category)

**Expected behavior**

The service should always respond with the right answer (using full index) or eventually pausing until it has full index or returning a 503.

**Proposed solution**

The right way to implement that:
* make indexes name alias instead
* for each index, export_index_data should:
  * populate a new index with a timestamped name
  * make alias point to the new index when ready
  * remove older index

Alternative would involve, putting a marker so that we can wait or return 503, but this seems like a thougher path for a less convenient result.

see also: https://github.com/openfoodfacts/robotoff/pull/478#r734330107

**Comment by raphael0202** [comment]
Elasticsearch is not used anymore for product categorization or for spellchecking (I still have to remove the associated codebase).
