### ISSUE TITLE
Robotoff asking questions already for existing values

### ISSUE THREAD

**Issue by hangy** [openfoodfacts/robotoff#52]
From openfoodfacts/openfoodfacts-server#1790 by @CharlesNepote

> I've just completed quantity (with the correct value) and robotoff is asking to confirm quantity value. I'm confused.
> ![image](https://user-images.githubusercontent.com/562352/58085942-fde21b80-7bbd-11e9-9764-0f9c3de12e78.png)

**Comment by raphael0202** [comment]
We receive real-time notifications when a product is updated, but this update is only used to predict the category. We could use it to delete invalid product weight insights.

**Comment by raphael0202** [comment]
Fixed in db96bcbec0beb8078ae4381ff1f2bc8099bb0802
