### ISSUE TITLE
Add insight_id to edit comment

### ISSUE THREAD

**Issue by hangy** [openfoodfacts/robotoff#54]
Have you considered adding the `insight_id` or actual URL to the insight when editing a product? That could help figuring out which source an edit was based on.

**Comment by raphael0202** [comment]
Good idea, it could be added to the comment of the update

**Comment by raphael0202** [comment]
It would also be easier if Robotoff was linked to a front-end, for easier debugging/moderation/reversal

**Comment by raphael0202** [comment]
Done (d3989e1f32af5346f67e1e26262f0147b7d83cff)
