### ISSUE TITLE
Make a clear distinction between predictions and insights

### ISSUE THREAD

**Issue by mithridatea** [openfoodfacts/robotoff#544]
## Current State

Currently, Robotoff primarily deals with insights. Originally, insights were a piece of information (label, product weight, category,...) that were predicted from images, image OCRs or other product information. All insights could always be either validated (and applied), rejected, or ignored.

However, some information extracted from images or OCRs did not fit well into this framework. For example, nutrition facts cannot easily be validated in a binary fashion: some nutritional facts (protein, salt,...) could be valid, others not.

Besides, every insight can be displayed on Hunger Games or Product Opener. Some information, such as detected nutrition mentions (presence of ”fibre” word for example) is not useful alone and was not saved as insights, even if it could be used in combination with other predictions to detect errors or generate “real” insights.

Finally, we dropped most detected insights during insight import: if the `en:organic` label was detected on multiple images of a product, only the first insight imported with this label was saved in DB, all other insights were discarded. This was unfortunate, as we can leverage information coming from multiple images to have increased confidence in the insight. Besides, storing all information extracted from multiple images opens up the possibility of dealing with conflicting insights (ex: distinct product weight detected).

To address these shortcomings, latent insights were introduced. All predictions were stored in the same `product_insight` table, most of them labeled with the binary flag `latent`. Only non-latent insights were displayed on Hunger Games or Product Opener.

Latent insights are either:

- insights that cannot be directly applied, because they don’t fit the ternary validation framework or because they shouldn’t be displayed on Hunger Games. Ex: `image_orientation` (detect the correct orientation of an image), `nutrient_mention` (detect “fibers” or “salt” on images, indicating that the product probably contains fibers or salt)
- remaining insights in case a non-latent insight already exists for the triplet `(barcode, insight_type, value)`. For example, if a `product_weight` insight exists for a product, all future `product_weight` insights are saved as latent. If this non-latent insight is rejected, one of the remaining latent insights is converted into a non-latent insight.

The introduction of latent insights helped us keep track of all extracted information. However, it did not solve completely the issues raised above, and introduced new issues:

1. The insight import process has become quite complex and difficult to understand
2. The process is not idempotent: the saved insights are not the same if we extract insights from N images or N * 1 image.
3. Due to the complexity of the insight import process, we currently don’t:
    1. generate complex insights based on multiple other insights
    2. leverage all predictions to generate insights: only a single prediction is used to generate an insight, all others are not used.

## Proposal

I suggest splitting:

- **predictions,** raw predictions generated from OCR using regex, ML models, or other heuristics. All predictions would be stored in a new `predictions` table.
- **insights**: predicted information about an OFF field. It can stem from a single or several predictions. Stored in the existing `product_insights` table.

All predictions would be saved in DB. Every time a product is updated (new/deleted image or updated information), all predictions associated with the product would be fetched, and insights of all types would be generated using this information. These insights would replace existing insights for this product that are not annotated.

This process is idempotent, i.e. generated insights are the same if no new predictions are added. Splitting prediction and insight generation allows us to be smarter during insight generation.

## Challenges

Even if this new framework allows us (in theory) to generate better insights, numerous challenges are still unresolved.

- How to deal with conflicting information? Ex: different product weights. Currently: the first product weight is marked as non-latent.
- Should information from old images be used to generate insights when more recent images are available? Probably not.
- When should an insight be applied automatically, when does it need manual validation? We should find a way to assess the insight confidence, including with insights stemming from multiple predictions.

**Comment by stephanegigandet** [comment]
The split into raw predictions and OFF specific field/value insights sounds quite good to me. It would give us a lot of flexibility for conflict resolution (e.g. not generating an insight if we have a conflict), choosing whether to apply an insight automatically etc.

**Comment by alexgarel** [comment]
I totally agree with the split. It will bring clarity. 

For challenge on images, I think we could use some law to give weight to images according to their freshness, but this is clearly a separate challenge.

**Comment by alexgarel** [comment]
I close the issue as I think it's all done :-)
