### ISSUE TITLE
Adding an higher level API for experimental ML extraction of nutrition

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/robotoff#549]
### Who for
- Smoothie devs
### What
- The API is too low level 
- Adding an higher level API for experimental ML extraction of nutrition
- From:
  - https://robotoff.openfoodfacts.org/api/v1/predict/nutrient?ocr_url=https://world.openfoodfacts.org/images/products/802/509/314/0251/4.json
- To
  - https://robotoff.openfoodfacts.org/api/v1/predict/nutrients?8025093140251&image=nutrition_fr
- Note: we don't seem to generate JSONs for nutrition_fr
  - https://world.openfoodfacts.org/images/products/541/067/300/4468/nutrition_fr.5.full.jpg
### Why
- We could have an initial auto-extraction mode
### Part of
- #372

**Comment by raphael0202** [comment]
We currently lack a good model for information extraction, after analysis the current approach doesn't work well for nutritional table. So it's better to add this once we have an accurate model.
