### ISSUE TITLE
Apply categories predicted by neural predictor directly ?

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/robotoff#552]
We have a good predictor for category as a neural network.

We want to apply categories automatically to gain lots of nutriscore.

However we don't know how to put threshold on category prediction

Just to give you an idea, some figures on my experiments on preprod.
I ask for categories on **562004** annonces from FR
Got **450580** predictions for **201397** annonces (36%)

**145385** annonces have neural prediction (25%) (the rest are prediction by ES on title)
and here is how many I have for different confidence threshold
0,5 --> **145385**
0,6 --> 133112
0,7 --> 120995
0,8 --> 105780
0,9 --> 81987

Now this does not gives a real idea where to put threshold. 

We could either:

- choose to look at it qualitatively, sampling some data for human check
- run experiments on threshold on our validation data set to see how much errors we do for different threshold

**Comment by kulizhsy** [comment]
I had done some analysis on what the good threshold value is and summarized it [here](https://docs.google.com/document/d/1oYb_O7pVlNF1jKX4jb3GeQEe6tliuJgQRWxOutv6kBU)

0.9 seemed like a reasonable threshold, as it was both the largest in terms of the number of predictions with this confidence, and also had the best correctness ratio.

One thing to note with my validation from the doc was that about 60% of predictions that were 'incorrect', were in fact good predictions based on manual inspection. So the accuracy of => 0.9 is likely even better.

**Comment by alexgarel** [comment]
Thank you so much @kulizhsy  ! I think this answer it's all I need.

I asked you access to the doc you are pointing.
Also if there is some scripts / notebooks / documentation material, I would be happy to get it (seems I miss some accesses). You can send them as an archive to me. I may then take the time to put important things to https://github.com/openfoodfacts/openfoodfacts-ai
