### ISSUE TITLE
Update of Elastic Search data should not happens blindly at startup

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/robotoff#558]
**Is your feature request related to a problem? Please describe.**

When you start the scheduler, it will invariably repopulate ES for category etc.

This is a problem because 
- on frequent deployment it may makes category prediction wrong until ES is updated
- on dev it takes time and consume CPU while not useful

**Describe the solution you'd like**

Schedule should check how old data are, eventually compare it to a specific settings (you want update to happens less in dev),
and decide to refresh index only if needed.

**Comment by raphael0202** [comment]
`product` index is currently unused (as we don't use spellcheck anymore).

I've disabled at scheduler startup :
- the automatic download of product dump (4bee57caf210873eb63cf541707bbb4554402165)
- the creation and update of `product` Elasticsearch index (c12f80326a289d2b68fe0e90af777736516aeb27)
