### ISSUE TITLE
push to pypi is failing

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/robotoff#566]
**Describe the bug**
https://github.com/openfoodfacts/robotoff/actions/workflows/pypi.yml all fails

**To Reproduce**
make a prod release --> it fails with an authentification error

**Expected behavior**
Should be able to upload.
Maybe username / password is wrong.

**Comment by alexgarel** [comment]
@mithridatea I think you own the package.

@teolemon I don't know if we have an openfoodfacts account ? 

And if @mithridatea  could give it rights on the project in pypi.

**Comment by rbournhonesque** [comment]
@alexgarel Sure, to who do I give rights?

**Comment by mithridatea** [comment]
@alexgarel Sure, to who do I give rights?

**Comment by alexgarel** [comment]
You should give rights to openfoodfacts (https://pypi.org/user/openfoodfacts/)

**Comment by alexgarel** [comment]
Hum finally @mithridatea alexg is better :-D

**Comment by teolemon** [comment]
We do have an openfoodfacts account (it's me) and an openfoodfacts package (a SDK) published automatically, if I remember well.

**Comment by teolemon** [comment]
actually no, release does not seem automated 🤔 
https://github.com/openfoodfacts/openfoodfacts-python

**Comment by teolemon** [comment]
and we still use travis: https://github.com/openfoodfacts/openfoodfacts-python/blob/develop/.travis.yml

**Comment by mithridatea** [comment]
I've added both `alexg` and `openfoodfacts` user as owner, you should have received an invite

**Comment by alexgarel** [comment]
This now works : https://github.com/openfoodfacts/robotoff/actions/workflows/pypi.yml
