### ISSUE TITLE
Consider dropping server_domain and server_type columns

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/robotoff#573]
Robotoff has a `server_domain` column and a `server_type` column.

This would permit to share a robotoff instance between two platform.

In practice, for now, the `server_domain` column is always the same. And with the volumes Robotoff handles, it could be more effective to have distinct database for distinct domains.

`server_type` as the same problem. Right now it's always off.
It's not sure why we use same models for different product opener instance type… if we do, maybe it would be in a specific robotoff instance.

The `sever_domain` has the drawback that we can't copy the prod database in preprod (which would be a good practice to catch errors early), for updating the very large tables using server_domain is more than 12 hours long…

I would advocate to:

- drop those columns in the database
- make the server_domain a settings 
- change the code using the column (models, queries, etc)

**Comment by alexgarel** [comment]
@teolemon, @stephanegigandet  and @mithridatea it's for discussion…

**Comment by teolemon** [comment]
I really want Robotoff for OxF projects sooner than later. I don't want to reduce the likelihood it happens.

**Comment by teolemon** [comment]
Also, I don't want this to be a way to block the Open Food Facts / Open Beauty Facts integration, that has to happen.

**Comment by alexgarel** [comment]
@teolemon but would you agree that we could drop the `server_domain` field and put it in a settings, linked to `server_type` column ?

```
SERVER_DOMAINS = {'off': 'api.openfoodfacts.org', 'obf': 'api.openbeautyfacts.org'}
```

This would only mean you can use robotoff for only one environment at a time.

**Comment by mithridatea** [comment]
For the record, from time to time we receive webhook calls from `api.pro.openfoodfacts.org`

**Comment by alexgarel** [comment]
ok, I close this issue then.

We would have to consider how to use prod data in preprod, maybe starting from a database dump and altering the content via sed.
