### ISSUE TITLE
Logo Annotations are not applied anymore in production

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/robotoff#597]
### What

- After latest deployment, Logo Annotations are not applied anymore in production.
- Might be related to #495 (fixed and then reopened)

### Part of 
- #596

**Comment by alexgarel** [comment]
I've seen today that the logo-annotation is created but no prediction / insight.

I think the best is to write an integration test.

**Comment by alexgarel** [comment]
@teolemon can you confirm it's fixed ?

**Comment by teolemon** [comment]
Waiting for Molinera to be applied to this: https://world.openfoodfacts.org/product/8410280294235/jus-de-poire

**Comment by raphael0202** [comment]
This feature is working, I checked in production. I'm closing this issue, feel free to open it again if a regression occurs.
