### ISSUE TITLE
Moderations alerts are broken

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/robotoff#598]
### What
- Moderations alerts are broken in moderation-off-alerts
- Might be related to the reopening of #495

**Comment by alexgarel** [comment]
The problem is a deployment problem :
- we do not add SLACK_TOKEN in deploy action
- `ROBOTOFF_INSTANCE` is set to "org" instead of "prod"

I will release a hotfix for production

**Comment by alexgarel** [comment]
This is done through the v1.1.0-hotfix1 tag.

We will need to merge the hotfixes branch in master https://github.com/openfoodfacts/robotoff/pull/601
But for now I'm testing in preprod.

**Comment by alexgarel** [comment]
It's merged.
