### ISSUE TITLE
Annotate should not raise

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/robotoff#605]
**Describe the bug**

Called by process_insights, annotator.annotate reraise the exception if one happens
but we do not catch it in process_insights.
This means that if an exception happens for one insight, we wont be able to run the other insights !

This might block any insight to be process because of a bug in one of them...

**Expected behavior**

We should catch exceptions in process_insights.

Also inside annotate, normally the try / except should be outside the db.atomic(), which will run the rollback as it sees the exception in its `__exit__` (see [peewee code](https://github.com/coleifer/peewee/blob/master/peewee.py#L4250))

**Comment by alexgarel** [comment]
@mithridatea do you agree ?

**Comment by mithridatea** [comment]
Yes, we should either catch the exception in `process_insights`.
We should also treat differently exceptions that come from request errors when calling the Product Opener API (that could occur once in a while) from other exceptions that should be logged in Sentry.
