### ISSUE TITLE
AnnotationResult should be stored in database

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/robotoff#606]
**Is your feature request related to a problem? Please describe.**

When robotoff processes an insight (process insight), an action may happen or not. Annotator.annotate return a useful AnnotationResult giving informations of what really happens : UPDATED_ANNOTATION_RESULT, MISSING_PRODUCT_RESULT, ALREADY_ANNOTATED_RESULT etc.

This is a very useful info when you want to know which insight did really have an impact. But currently this is not stored in the database.
This would be useful for stats and for debugging.

**Describe the solution you'd like**
Associate each AnnotationResult with a number and store it in `annotation` column (instead of a simple 1).

Alternatively, if this is not compatible with current code, We may store this info in another column.

**Comment by alexgarel** [comment]
@teolemon annd @mithridatea you're opinion matters.

**Comment by Jagrutiti** [comment]
Hi @alexgarel 

I would like to take this up. 

If I am not wrong this is the file in question
 https://github.com/openfoodfacts/robotoff/blob/master/robotoff/insights/annotate.py

Could you guide me at what point shall I save the data?

> Associate each AnnotationResult with a number and store it in `annotation` column (instead of a simple 1).

By this, you mean the PostgreSQL database? Would I need database dump or something? Because database setup instructions are not mentioned in the readme or contributing file.

**Comment by alexgarel** [comment]
If you can run the tests, it means you have a database set up !

At first launch database is created, it is managed by peewee. See https://github.com/openfoodfacts/robotoff/blob/master/robotoff/models.py (you may also find database creation).

But at the moment we do not handle migrations (we have not many deployment, so we handle it manually…).

But you are right that we do not provide sample data and this is a problem, we should provide a sample dump of a few rows of each table. I will see if I can work on it, but it does not stops you.

**Comment by alexgarel** [comment]
Btw a quick way to create some data is to use the factories in https://github.com/openfoodfacts/robotoff/blob/master/tests/integration/models_utils.py (in a python console that you can launch with poetry run python).

**Comment by Jagrutiti** [comment]
Hey @alexgarel 

You were right about having a database setup while running test cases, also got the database structure. 

Got this URL: https://robotoff.openfoodfacts.org/api/v1/insights/ from Hunger games to fetch insight. 

From [api.md](https://github.com/openfoodfacts/robotoff/blob/master/doc/references/api.md#insight-annotations-insightsannotate) I understood to save we call `insights/annotate`

`save_insight` is written in [cli/annotate.py](https://github.com/openfoodfacts/robotoff/blob/master/robotoff/cli/annotate.py#L71). Maybe I will have to write the logic here (not sure though)

What is the difference between  [cli/annotate.py](https://github.com/openfoodfacts/robotoff/blob/master/robotoff/cli/annotate.py) and [insights/annotate.py](https://github.com/openfoodfacts/robotoff/blob/master/robotoff/insights/annotate.py)? 

Is there a router file where an API path is mapped to a method? The URLs are defined in `settings.py` but I didn't find the mapping with methods. How to figure out which URL calls which method?

**Comment by alexgarel** [comment]
It's done !
