### ISSUE TITLE
Use the new popularity facet to propose products with impact

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/robotoff#62]
Use the new popularity facet to propose products with impact: we have the top 1000k product, the top 10k products. Allow to return popular products to Hunger Games to maximize impact
https://world.openfoodfacts.org/popularity/top-1000-scans-2019

**Comment by raphael0202** [comment]
@teolemon What is the field associated with this facet?

**Comment by teolemon** [comment]
It's not currently exposed as a field. We either have to work around it or wait for @stephanegigandet to expose it.

**Comment by raphael0202** [comment]
This is available as the `unique_scans_n` field. I've added a new `/questions/popular` endpoint that return insights of products ordered by popularity.
