### ISSUE TITLE
Switch from Tensorflow Serving to Triton

### ISSUE THREAD

**Issue by mithridatea** [openfoodfacts/robotoff#622]
We currently use Tensorflow Serving to serve all models:
- object detection models  (nutriscore, universal-logo,...)
- category classifier model

However, Tensorflow Serving only supports the SavedModel format, which is specific to Tensorflow. It means we cannot easily integrate models trained with other frameworks (pytorch, scikit-learn,...).

ONNX is a standard format to save model architecture and weights supported by all major frameworks, including Tensorflow, Pytorch and scikit-learn.

## Proposal

Test Triton, an open-source inference server developed by Nvidia. Supported formats include TF SavedModel and ONNX. Runtime on both GPU and CPU.
If tests are successful, switch from Tensorflow Serving to Triton server.

**Comment by ram690514** [comment]
I am interested to work on this issue , if no one is currently working on it

**Comment by raphael0202** [comment]
The switch to Triton is done in preprod, closing this issue.
