### ISSUE TITLE
Use OpenAPI to document Robotoff API

### ISSUE THREAD

**Issue by mithridatea** [openfoodfacts/robotoff#623]
Currently, the Robotoff API is partially documented in https://github.com/openfoodfacts/robotoff/blob/master/doc/references/api.md, in the Blueprint API format.

Switch API documentation to a more recent and widely adopted API format such as OpenAPI. Many renderer exists, such as redocly to render the API and play with it: https://redocly.github.io/redoc/

Example: https://redocly.github.io/redoc/?url=https://openfoodfacts.github.io/robotoff/api.yml

**Comment by alexgarel** [comment]
It's about using a tool to generate .md files from the openapi description (which is in the api.yml if I'm correct). The tool have to be integrated to be run automatically on documentation deployment (this is a github action) to generate the file: in generate-docs.yml and in doc target in Makefile (though that would be cool to have generate-docs use make docs !)

**Comment by alexgarel** [comment]
First step: find the right tools to generate open api (json or yaml) from the source code.

**Comment by alexgarel** [comment]
see https://pypi.org/project/falcon-openapi/  maybe

**Comment by alexgarel** [comment]
See https://github.com/falconry/falcon/wiki/Add-on-Catalog

> [falcon-apispec](https://github.com/alysivji/falcon-apispec) [APISpec](https://github.com/marshmallow-code/apispec) plugin that generates OpenAPI specification (aka Swagger) for Falcon web applications
> [py2swagger](https://github.com/Arello-Mobile/py2swagger) OpenAPI specification generator

**Comment by raphael0202** [comment]
After discussion with @alexgarel, we're going to directly right the documentation in doc/references/api.yml, without using an automated method to generate the documentation from the source code.

**Comment by raphael0202** [comment]
Done, OpenAPI API is now used: https://github.com/openfoodfacts/robotoff/blob/master/doc/references/api.yml
