### ISSUE TITLE
Add Robotoff HTTP header for JSON requests

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/robotoff#63]
xxx - - [24/Jun/2019:15:32:34 +0200] "GET /images/products/356/470/710/7846/7.json HTTP/1.1" 200 13834 "-" "python-requests/2.21.0"
xxx - - [24/Jun/2019:15:32:34 +0200] "GET /images/products/356/470/710/8003/4.json HTTP/1.1" 200 8106 "-" "python-requests/2.21.0"

**Comment by hangy** [comment]
Like the user-agent?

**Comment by raphael0202** [comment]
Yes in the User-Agent. The simplest way of doing this across requests is to specify the user agent in the `http_session` object in off.py, and to use it across all off requests.
Seems like an easy task for a new contributor :)

**Comment by CloCkWeRX** [comment]
Didn't f8dc78d6df7fcedd14655169c748c2bc3184622e add this to add http_session.get calls? 
It could be refactored to ```http_session.headers.update({'user-agent': ...})``` but should be working from a cursory glance?

**Comment by raphael0202** [comment]
The commit mentioned only added the user agent for product updates, not for other requests (image download,...)

**Comment by raphael0202** [comment]
Done for all requests (97cf4de4dc5a6d7e85caef41a785fb22bb435653)
