### ISSUE TITLE
Robotoff tests should not depend on fetching external taxonomies

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/robotoff#649]
### What
In insights/units/insights/test_importer.py there are tests that when run, ultimately make the code call `fetch_taxonomy` (through `TAXONOMY_STORES`).

This is bad practice, as having openfoodfacts.net means tests won't run, but also you won't understand why tests are failing in an evident manner. More over those are unit tests, they should not depends on external resources.

### Steps to reproduce the behavior:
1. clean you data/taxonomies folder
2. make openfoodfacts.net not accessible, eg. modifying your /etc/hosts
3. run tests
4. this breaks

### Expected behavior
Tests should not break depending on external conditions.

We should instead mock `fetch_taxonomy` (see how it's done in `test_annotate_image.py`) returning consistent infos for tests to run.

**Comment by raphael0202** [comment]
As the PR is merged, I'm closing the issue.
