### ISSUE TITLE
EU-/Nicht-EU-Landwirtschaft

### ISSUE THREAD

**Issue by hangy** [openfoodfacts/robotoff#65]
There's several products where robotoff sees "Nicht EU-Landwirtschaft". However, the full text is "EU-/Nicht-EU-Landwirtschaft" in German (or "EU/ non-EU agriculture"  in English). If possible, these combinations could be detected and excluded using a negative lookbehind, so that users don't mistakenly add the incorrect "non-EU agriculture" label.

insight_id: 14ffbf39-181c-4dd3-b50c-ce874e91ab63

**Comment by raphael0202** [comment]
There is currently a negative lookbehind on the english regex (`(?<!-)\s?eu agriculture`), the false positive I've seen always resulted in an incorrect detection from the OCR (the `-` character wasn't detected). If you think the regex can be improved in any other way, feel free to make suggestion :)

**Comment by hangy** [comment]
I didn't have the image id/OCR link available when I created this issue, but I guess a bad OCR is a likely issue for it. I'll revisit this issue when I see additional occurrences.

**Comment by raphael0202** [comment]
My bad, the issue doesn't come from a missing comma in  this case. Actually the insight is quite old (https://robotoff.openfoodfacts.org/api/v1/insights/detail/14ffbf39-181c-4dd3-b50c-ce874e91ab63), it was generated on February 2019. At this time, we didn't have support for en/non-eu agriculture label.
I'm closing the issue, feel free to reopen if you find additional occurrences which can be fixed.
