### ISSUE TITLE
German Packager Code two-letter number 

### ISSUE THREAD

**Issue by hangy** [openfoodfacts/robotoff#66]
https://github.com/openfoodfacts/robotoff/blob/e5534b488a988c23cc2c56fbf59d01384d7130c5/robotoff/insights/ocr/label.py#L38

Some packager codes like `DE-ÖKO-001` always need three-letter numbers. Robotoff sometimes suggests labels like `DE-ÖKO-00`, which is never valid. There is no need to create an insight for this, if the full pattern was not found.

**Comment by raphael0202** [comment]
Fixed in 34bf3ed27906c55676f5de24dd57e83fa39f00d8
