### ISSUE TITLE
Improve random question performance

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/robotoff#664]
## What

Today in `app.core.get_insights` we use `order by random() * (n_votes + 1)` to have random rows from the database.

This is something which is not performant on postgresql.

## Possible solutions  ?

Not sure if there is a simple solution, or even a better solution at all.

This [stackoverflow response](https://stackoverflow.com/a/8675160/2886726) is quite exhaustive

Postgres propose [TABLESAMPLE])https://www.postgresql.org/docs/current/sql-select.html#SQL-FROM) and there also is a [tsm_system_rows](https://www.postgresql.org/docs/current/tsm-system-rows.html) extension (see this [blog post](https://www.redpill-linpro.com/techblog/2021/05/07/getting-random-rows-faster.html)) which is a more efficient version of tablesample. 

The problem is that combined with a where clause (especially if it is more restrictive) it might return less or no data.
Should we give a first try with a sampling at 10% and then if we have not enough rough (which means not many matching row) go for the old technic ?

[tsm_system_time extension](https://www.postgresql.org/docs/current/tsm-system-time.html) might also provide a better solution as it is a "timed" box version, there again we could rely on this and fall-back to the classic method if needed.

**Comment by raphael0202** [comment]
Questions are now sorted by popularity by default, so it's not an issue anymore. We can reopen if we switch back to random sorting.
