### ISSUE TITLE
Have a route to list insight opportunities for a given type of tags

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/robotoff#676]
### What

The problem is that we have thousands of categories, so we should send thousands of requests to robotoff for just knowing which category has at least one question to answer.

A better option is to have a route returning something like that
```
{
	"remaining_category_to_validate": {
		  "en:waters": 10,
		  "fr:lasagnes": 3,
		  ...
	  }
}
```

Parameter would be type of insights (eg. type=category, or type=labels)

We should also be able to paginate, and sort on quantity.

If possible add an agribalyse=True filter (it use categories.json to get agribalyse and filter on them, eventually on python side).

### Why

Useful for games on bonus / malus for eco-score (avoid making 5 or 6 requests).

Useful to get data for eco-score (agribalyse)

### Part of
- #374

**Comment by alexgarel** [comment]
This issue is solved.
