### ISSUE TITLE
Integrating Curvature Correction in Robotoff

### ISSUE THREAD

**Issue by HARSH-nith** [openfoodfacts/robotoff#688]
### Problem
We are currently using Google Vision OCR in robotoff for extracting nutrition table data from images.
The performance of google vision OCR is good, But the main drawback with google OCR is that **it performs very badly with the images having non-aligned curvature.** Due to this problem, we are unable to extract nutrition tables from packages like bottles and jars.

### Proposed solution
Curvature Correction is a smart approach that we can employ to solve the issue of nonaligned curvature. **I think that we can use curvature correction as an image pre-processing technique**. 
Through this technique, the image will be pre-processed before being given to Google Vision OCR for extraction of nutrition table data from it.
I am planning to integrate the curvature correction feature into robotoff.

**Comment by teolemon** [comment]
That would be awesome, even beyond OCR (to get flat images on bottles)
Related to https://github.com/openfoodfacts/openfoodfacts-ai/issues/53

**Comment by raphael0202** [comment]
This issue is currently an R&D project, so it belongs to openfoodfacts-ai repository. I'm closing this issue, we can open it up again once we have results.
