### ISSUE TITLE
Quantity detection: Try to exclude matches for "4x45g" and similar.

### ISSUE THREAD

**Issue by CloCkWeRX** [openfoodfacts/robotoff#69]
Right now; the model will often detect the weight as "45 g" when given "4x45g"

If possible, a detection of this should invalidate other quantity detections.

These products worked:
https://world.openfoodfacts.org/product/5603722513565/magro-aroma
https://world.openfoodfacts.org/product/3701002401006/compote-pommes-fraises-maitre-papilles

While others have not
https://world.openfoodfacts.org/product/3302749338022/le-batonnet-moilleux-fleury-michon

https://robotoff.openfoodfacts.org/api/v1/questions/3302749338022?lang=en
```
{"questions": [{"barcode": "3302749338022", "type": "add-binary", "value": "500 g", "question": "Does this weight match the weight displayed on the product?", "insight_id": "282b8b1b-45e2-4d9f-b549-da3fa9d7ca6d", "insight_type": "product_weight", "source_image_url": "https://static.openfoodfacts.org/images/products/330/274/933/8022/1.400.jpg"}], "status": "found"}
```

**Comment by raphael0202** [comment]
"4x45g" does invalidate "45g" insights.
The "Y x Xg" pattern came after the simple pattern, the last insight is an old insight (2019-03-31), the multipackaging support was added later (https://github.com/openfoodfacts/robotoff/issues/21)

**Comment by raphael0202** [comment]
Feel free to reopen the issue if you find a recent insight with this problem.

**Comment by CloCkWeRX** [comment]
Ah, thanks! Didn't realise I was looking at old insights
