### ISSUE TITLE
Adding MongoDB docker to Robotoff

### ISSUE THREAD

**Issue by Jagrutiti** [openfoodfacts/robotoff#692]
### What
When trying to run Robotoff's `save_annotation` I encountered the error saying missing connection to MongoDB.
![Screenshot from 2022-04-08 19-55-47](https://user-images.githubusercontent.com/28809492/162572990-ad50fe02-08f1-46ee-a6b5-3aff5185a10f.png)

For now the only solutions we have is:

- install perl server and run it with docker, aka openfoodfacts-server (eats lot of memory)

- add a mongodb docker in the same network and configure robotoff to use it

Here is a reference to the [Slack discussion](https://openfoodfacts.slack.com/archives/CF0286BRQ/p1649429663590889?thread_ts=1649345138.680329&cid=CF0286BRQ) about the same.

### Steps to reproduce the behavior:
1. run `docker-compose up`  
2. Try to execute the function in [pdb](https://docs.python.org/3.8/library/pdb.html) with these parameters:
`core.save_annotation(insight_id='3e168efb-6c5d-4933-bb32-a928cd0dc0ae',annotation=1,device_id='57321fd2a838d4c11db6d7b0926c681d6ac5c543',update=True,data= None,auth= None,trusted_annotator = True)
`
4. See the execution breaking in the middle.

**Comment by raphael0202** [comment]
As the PR is merged, I'm closing the issue.
