### ISSUE TITLE
Generate a dump of logos and labels from Robotoff-ANN and Product Opener

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/robotoff#725]
### What

- [ ] Generate a dump of logos and labels from Robotoff-ANN and Product Opener

### Part of
- #596

**Comment by raphael0202** [comment]
What do you want to do exactly? Is it what you want (https://github.com/openfoodfacts/openfoodfacts-ai/releases/tag/dataset-logo-2022-01-21) ?

**Comment by teolemon** [comment]
closing
