### ISSUE TITLE
Frequent HTTP 502 errors on production deploy

### ISSUE THREAD

**Issue by CloCkWeRX** [openfoodfacts/robotoff#75]
Example errors:
![image](https://user-images.githubusercontent.com/365751/61874807-764fba80-af28-11e9-8be3-f20a0ee84282.png)

Example of quick succession of calls, with suddenly reduced performance:
![image](https://user-images.githubusercontent.com/365751/61876399-ef044600-af2b-11e9-90e2-ef3f6808d14f.png)

I'm not sure if this is robotoff or the openfoodfacts server itself; by I commonly experience HTTP 502 errors from the frontend.
It may be I'm in a timezone where bulk operations are scheduled to run, or similar; or rate limiting kicking in.

I'm mainly focused on calls involving InsightType.category.name: CategoryAnnotator()

What I observe is my initial POST to the annotate API
 - Holds open a connection from me to openfoodfacts to robotoff
 - Loads product details from openfoodfacts in robotoff
 - Performs some basic logic
 - Writes an update via a HTTP call to openfoodfacts
 - Writes an update to elasticsearch to change the status of the insight via a HTTP call

It feels like with the JS frontend, I'm able to quickly wrack up 5 calls in `5-6 seconds; resulting in a corresponding 25 calls via robotoff happening on my behalf, and 5-6 calls to the API to get product details, etc.

**Comment by raphael0202** [comment]
@CloCkWeRX Do you still experience this issue? robotoff is hosted on the dev server, where product opener eats much of the RAM. So we have occasional kill of the service due to memory exhaustion.

**Comment by CloCkWeRX** [comment]
I have seen some big periods of slowdown, subjectively I would say a little less often that when I wrote this originally. I can keep an eye on it for the next while; and just close if I haven't added more detail in a few weeks time.

**Comment by CloCkWeRX** [comment]
It seems a lot more stable at the moment. Closing.
