### ISSUE TITLE
Extract AOC from images

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/robotoff#78]
### What
- Extract AOC from images to match AOC categories (especially for wine bottles)
  - "Appellation Clairette de Dié contrôlée"
  - "Appellation * contrôlée"
  - https://static.openfoodfacts.org/images/products/325/622/711/0559/1.jpg
  - https://static.openfoodfacts.org/images/products/325/622/711/0559/1.json
- Save as a category insight
### Part of
- https://github.com/openfoodfacts/robotoff/issues/600

**Comment by alexgarel** [comment]
see also labels taxonomy to see the translation in different languages

**Comment by raphael0202** [comment]
Implemented, closing the issue.
