### ISSUE TITLE
Extract storage temperature to enable biasing ML algos

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/robotoff#79]
### What
Extract storage temperature to enable biasing ML algos for category classification

inferior to 7°C : "Charcuterie, produits à base de crème patissière"'
inferior to 4°C: "Viande hachée, volaille, poisson"
inferior to -19°C: "surgelés"

according to Test Achats

**Comment by raphael0202** [comment]
As this is not sure store temperature add some signal to category prediction, I'm closing this issue (no need to extract it if we're not leveraging it)
