### ISSUE TITLE
we still need 3 votes (sent with user id) to get the question answered definitely

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/robotoff#801]
> mmmh… It was one hour ago, and didn't give you credit: https://world.openfoodfacts.org/product/2817896019485/st-nectaire-aop-laitier

The answers are resent in the end of questionnaire (after login) with user id.
I don't know how it works on the server side,  you mean if we send an answer with user id, we do not need to have the other votes? I am not sure about it ... since I tried with my account, we still need 3 votes (sent with user id) to get the question answered definitely (to have those scores )...

_Originally posted by @cli1005 in https://github.com/openfoodfacts/smooth-app/issues/2117#issuecomment-1143568155_

**Comment by alexgarel** [comment]
@teolemon we wrote the test and we do not reproduce the cited behavior. If we vote anonymously and, just after, answer question being authenticated, this works.

So the problem might be on the app side ? (eg. the authentication is not immediately taken into account ?)
