### ISSUE TITLE
"Is this nutrition fact correct ?"

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/robotoff#83]
I was thinking of adopting an atomistic approach, nutrient by nutrient, for nutrition facts, that mostly matches the current Robotoff structure. 

Photo
"Is this nutrition fact correct ?"
Yes - No [Box to enter the value]

Volumetry: 7 facts per product * 725755 products with photos uploaded = up to 5 million facts to check
We would check in priority products with wildly aberrant values, and old products with a recent scan

**Comment by raphael0202** [comment]
It turned out it was easier to store all nutrition facts coming from 1 image under a single prediction.
