### ISSUE TITLE
TestLabelInsightImporter should not depend on external data

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/robotoff#833]
### What

TestLabelInsightImporter depends on taxonomies served by openfoodfacts.
This has several drawbacks:
1. it might prevent a coder to test his code because of low internet bandwidth or the .net server being down (happens to @Jagrutiti )
2. it makes the test fails without warning and without any change to the code, on some taxonomy changes (happens this week) 

### Expected behavior

Test should only depend on data provided with the code.

We should have a simple json for each taxonomy we use in tests with several categories, that we could use it to monkeypatch `robotoff.taxonomy.get_taxonomy`.

### parts of

#649

**Comment by raphael0202** [comment]
We already have a JSON for each taxonomy locally (which is the fallback version in case of network error)

**Comment by alexgarel** [comment]
@raphael0202 you have it if you're not on a fresh install, here running test eg. in CI means you are on a fresh install. (Or I am wrong ?)

**Comment by raphael0202** [comment]
Even on a fresh install the taxonomies are available here: https://github.com/openfoodfacts/robotoff/tree/master/data/taxonomies
But I just noticed a bug for brand taxonomy, it fallbacks by default (after request timeout) to the label one
