### ISSUE TITLE
Make face recognition more efficient by using faceAnnotations

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/robotoff#86]
We only trigger an alert when ('Face', 'Head', 'Selfie'). We could expand it to Man/Woman but we could make face recognition more efficient by using `faceAnnotations` when it is present.

**Comment by raphael0202** [comment]
I've added the detection of many other labels, and lower the detection threshold (see 9eb0eeda7ac10c43bedd59be7e1994e4af77438f). This should be sufficient to detect many more spam images. I haven't found a case where faceAnnotations were present without their associated labels, so I don't think it's necessary to add it.
