### ISSUE TITLE
Devops - Add facilities to allow automonous dev

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/robotoff#895]
### Problem
- You need to have a working install of Product Opener, with JSONs and images, and products to allow Robotoff to work
- Product Opener is notoriously heavy

### What
Devops - Add facilities to allow automonous dev

### Proposed solution
- Add a small FastAPI server with:
  - JSON OCRs
  - Images
  - The ability to simulate a ping Robotoff with arbitrary payloads
  - small taxonomies json ?
- For write test, we can probably do with .net
- add an optional mongodb database
- ask for a mongo export of sample data on the product opener side

**Comment by alexgarel** [comment]
Good idea, I added mongodb.

> - For write test, we can probably do with .net
Really we should not !

**Comment by raphael0202** [comment]
We don't need a Product Opener docker install locally for Robotoff, in fact I never used one.
Robotoff is connected to preprod by default locally.
With the new `ENABLE_PRODUCT_CHECK` parameter (set to 0 locally) we don't perform product check against the MongoDB, which makes development easier (no need to have a MongoDB running for simple checks).
And we added MongoDB to the docker compose file.

> The ability to simulate a ping Robotoff with arbitrary payloads
We have a new `import-image-webhook` CLI that allows to simulate easily the import of an image of robotoff locally.

> ask for a mongo export of sample data on the product opener side
The process to import MongoDB data locally is described in the doc.

I'm closing this issue, feel free to reopen if other devops issue comes up.
