### ISSUE TITLE
Allow filtering unanswered questions by product country

### ISSUE THREAD

**Issue by alexfauquette** [openfoodfacts/robotoff#901]
The idea would be to ask hunger game users which country interest them and display the top question for their country

**Comment by alexgarel** [comment]
@Jagrutiti would you like to tackle this one while it's fresh ? :-)

**Comment by Jagrutiti** [comment]
We can add a country parameter to the `UnansweredQuestionCollection` API.

The good thing is `get_insights` already has a country parameter to filter. We only have to pass it through the API.

Once you confirm the solution I can start working on it. @alexgarel

**Comment by alexgarel** [comment]
Yes it's as you said @Jagrutiti !

**Comment by raphael0202** [comment]
Fixed
