### ISSUE TITLE
List categorization questions for agribalyse

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/robotoff#902]
Since:
- #676

we now have an API to list categorizations opportunities by type of questions.

But our goal is
- https://github.com/openfoodfacts/hunger-games/issues/39

To do that, we would like to have the same request but only for agribalyse categories

An flexible way to do that is to add a parameter with_property=agribalyse_food_code

That will:
1. search for all values in the taxonomy that have this property (here: agribalyse_food_code)
2. in the request filter the value_tag using the "IN" operator

Implementation details to be discussed

**Comment by raphael0202** [comment]
During insight creation we may also set a flag in data->is_agribalyse_category, I think it would be the simplest way of doing it.
But we should first discuss the relevance of categorizing agribalyse-specific categories in priority, I'm not convinced yet it's the best approach.

**Comment by alexgarel** [comment]
@raphael0202 later on, we could even add an API to add a list of codes to a campaign :-) and maybe integrate it with mass edit or something like that. So that any advanced user could create a campaign.

**Comment by raphael0202** [comment]
Implemented, closing the issue.
