### ISSUE TITLE
Make the skip mechanism only for user

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/robotoff#908]
### Problem
When a user skip a question, it is no more available to anyone,
while most of the time user skip it only because he does not know enough on the category or has not enough bandwith for now.

### Proposed solution

Use AnnotationVote for that instead.
It seems to me it will work out of the box !
Instead of storing as an annotation the "skip", store it as an AnnotationVote.

### Part of
- #374

**Comment by sumit-158** [comment]
@alexgarel Is it okk If I work on this? If yes, what is the target file?

**Comment by alexgarel** [comment]
@raphael0202 is the one setting priorities ;-)
