### ISSUE TITLE
Clarify human edit vs automated edit

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/robotoff#91]
```
EDIT: Au temps pour moi, c'est le robot qui fait n'importe quoi :
(app)[robotoff] Adding category 'en:baker-s-yeast', ID: 25908f1e-99d7-4e8b-8e16-5d6c68c21b28 (automated edit)
``` 
Tacite was confused by a robotoff edit on behalf of a user. Perhaps clarify like so:
"automated edit of behalf of ID: wwwww" ?

**Comment by raphael0202** [comment]
This has been taken care of, and will be effective as soon as the session cookie is sent to Robotoff.
The `(automated edit)` won't appear if the session cookie is sent along the annotation request, and  the update will be linked to the user history.
