### ISSUE TITLE
Support annotation campaigns

### ISSUE THREAD

**Issue by raphael0202** [openfoodfacts/robotoff#947]
Enable adding insights to "annotation campaigns", to focus on a subset of products.

Use cases:
- focus on agribalyse category questions (https://github.com/openfoodfacts/robotoff/issues/902)
- focus on products with specific caracteristics

This allows us to avoid creating too many filters on Robotoff API side.

# Description
Add `campaign` field to `product_insight`, which is a list of string (JSONB) that can be used to create "annotation campaigns" and to select only a subset of questions during question retrieval.

And we would display only insights from this campaign with:
https://hunger.openfoodfacts.org/questions?type=category&campaign=CAMPAIGN_NAME

For short campaigns, only a DB update would allow adding the tag to specific products. As suggested by @alexgarel, we could later add an API to create annotation campaigns directly on Hunger Games (probably for moderators only).

# DB Migration

```sql
ALTER TABLE product_insight
ADD COLUMN campaign JSONB NOT NULL DEFAULT '[]'::jsonb;

CREATE INDEX product_insight_campaign ON public.product_insight USING GIN (campaign);
```

**Comment by teolemon** [comment]
Another nice usecase beyond the ones discussed today might be all products bearing children of a category, eg: all products with children categories of the wine category could have an openwinefacts campaign.

**Comment by raphael0202** [comment]
Implemented, closing the issue.
