### ISSUE TITLE
Allow to rank questions by confidence and filter by predictor in Robotoff

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/robotoff#949]
### Problem
- Allow to rank questions by confidence and filter by predictor in Robotoff, for use by Hunger Games (and possibly more)
- confidence: that should allow to see the easiest ones first. predictor: focus on specific predictors that we know are very effective.
- Raphael says: "we should create a new DB field in Robotoff" (for confidence)

### Downstream issue
- https://github.com/openfoodfacts/hunger-games/issues/266

**Comment by raphael0202** [comment]
Both are now implemented: https://openfoodfacts.github.io/robotoff/references/api/#tag/Questions/paths/~1questions/get
