### ISSUE TITLE
Add a sort parameter to insight collection API

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/robotoff#968]
The insight collection API do not support a "sort" parameter.

For facets knowledge panels  we would like to sort them by annotation time. See https://github.com/openfoodfacts/facets-knowledge-panels/issues/43

**Comment by raphael0202** [comment]
As we've disabled most queries made by Facet Knowledge Panel (due to performance constraints), I'm closing temporarily this issue until we decide what to do.
