### ISSUE TITLE
Expose an API route to expose Robotoff predictions for nutrition facts

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/robotoff#987]
### Problem

- Expose an API route to expose Robotoff predictions for nutrition facts
- The data is currently stored in the Prediction table. 
- A new route should be created to return the best prediction for a given product.
### Related to
- https://github.com/openfoodfacts/smooth-app/issues/3278
- https://github.com/openfoodfacts/hunger-games/issues/74
### Part of
- #372

**Comment by raphael0202** [comment]
We can already use the `/predictions` route to get all nutrient predictions associated with a product:

https://robotoff.openfoodfacts.net/api/v1/predictions?types=nutrient&barcode=3017800502044
